### ISSUE TITLE
Malware complaining by Chrome

### ISSUE THREAD

**Issue by veltall** [Pulover/PuloversMacroCreator#10]
Both the website and the executable downloaded from Softpedia are flagged by Chrome as malicious.

[wedsite and downloaded executable are both blocked in Chrome](http://i.imgur.com/qff0v2R.png)

I followed their links and came to this guide for resolving this issue from your side: https://support.google.com/webmasters/answer/3258249

**Comment by SamHasler** [comment]
For interested potential users, this is the virustotal report:

https://www.virustotal.com/en/file/16a86d7955b374cfad78725b3b23e1a03df98445974feadfe19d87db12c411de/analysis/

**Comment by SamHasler** [comment]
Since I've heard of AVG and not Antiy-AVL or VBA32 I've submitted the installer to http://www.avg.com/submit-sample.tpl-stdfull

Will update if I get a response

**Comment by SamHasler** [comment]
AVG no longer reports it as a virus. I've emailed the companies for the remaining two false positives.

**Comment by Pulover** [comment]
Hi veltall and SamHasler,

Thank you for the warning and help. I am aware of the problem for some time, but could not find time to fix this before. I am currently working on a major update of PMC and also updating the website, which is currently under maintenance. I have checked the issue on google and I know what happened, it wasn't any virus, just a down time that caused the problem. However I need to finish the update and the changes on the site before I can I open it for google bot. It will be fixed soon.

**Comment by Ickorus** [comment]
Will be nice when the matter is resolved and executable deemed safe.

**Comment by jleaders** [comment]
Firefox also reports it as a virus. When will this be fixed? Until then people won't use your product

**Comment by Pulover** [comment]
I already explained that. If you check the changes on the Dev branch you'll see how much I'm working on the update. This is a freeware, I don't make an income out of it and I don't care how long it will take to implement and fix everything I want to. The website will be back when I finish it.

The current version is available for download in the GitHub release.

**Comment by jleaders** [comment]
We appreciate your work!

**Comment by Pulover** [comment]
The infection warning has been removed by Google. The website will remain in maintenance mode until the release of version 5.0.
