### ISSUE TITLE
Configurations/options reset 

### ISSUE THREAD

**Issue by xecxec** [Pulover/PuloversMacroCreator#102]
Every time i restart the client everything resets. I have to set up the options again every single time. And also it asks for layout/language like i installed it and ran it for the first time. One last thing is that it deletes my saved macro and backup file after crashes/restarts.

By any chance, does it prevent u in WoW from casting anything through mouse clicks or keyboard inputs after a while?

**Comment by Pulover** [comment]
Please, describe only one problem per issue. Configurations are saved in %AppData%\MacroCreator\Macrocreator.ini when the program is closed. This is working, so it must be something on your side.

**Comment by xecxec** [comment]
I have no such file in my appdata. no idea why.

**Comment by xecxec** [comment]
I have figured it out and fixed it. Your answer helped. Thanks a lot. ^^
