### ISSUE TITLE
Error: Parameter #3 must not be blank in this case.

### ISSUE THREAD

**Issue by bose2501** [Pulover/PuloversMacroCreator#107]
Hi,

Thanks for the recent update.

I tried to install multiple times but get this issue when running the program;

```
Error: Parameter #3 must not be blank in this case.

Line# 
---> 15845: Menu,PreviewMenu,(AutoRefresh) ? "Check" : 
"Uncheck",%v_Lang030%

The current thread will exit.
```

This pops up in a window with only 'Ok' as an option, and happens both when I run a macro save file and also when I run the program without running a macro I previously created.

**Comment by ozzhates** [comment]
I think this may interest you. https://github.com/Pulover/PuloversMacroCreator/issues/106

**Comment by Pulover** [comment]
Yes, delete the %AppData%\MacroCreator folder and install it again. It looks like I should have updated language file version. It's been so long since I last coded PMC that I don't remember all of its workings.
