### ISSUE TITLE
Random Quit

### ISSUE THREAD

**Issue by comtech1234** [Pulover/PuloversMacroCreator#11]
Running the latest Macro Creator on Windows Xp Sp3 and sometimes depending on what I click in the program or when I try to save it quits and gives me an error. Sometimes when saving it quits then deletes the original file I was trying to save.
![macroerror1](https://cloud.githubusercontent.com/assets/14913449/10222174/92198f6e-6820-11e5-9d90-61edce8e29f1.jpg)

**Comment by Pulover** [comment]
Hi,

Sorry for the late reply. I could not figure out what causes the crashes. I suggest you try to disable highlighting in settings. 

If you can provide me with steps to reproduce the problem I will investigate. Thanks.

**Comment by comtech1234** [comment]
I think this issue is purely Windows XP related. I've used this on a laptop
at work with vista and haven't had any issues. I'm upgrading my workstation
to windows 7 in the close future and probably won't have this issue again.
I think it has something to do with windows xp specifically. I can't
produce this error at a specific time. It just randomly closes when I
sometimes click on buttons or sometimes when the scripts loaded via
scheduler it just quits and gives me a random error. I am also unfortunate
to not find the logs for this error. I wonder if I can check the windows
error console when this happens and get a vague idea of what happens. Also
if I use the software teamviewer from a remote computer I can not reproduce
this error. So it could be client side involving mouse calls or hooks. Not
100% sure. Thanks for replying.

On Wed, Dec 9, 2015 at 5:30 PM, Rodolfo U. Batista <notifications@github.com

**Comment by comtech1234** [comment]
Event Type: Error
Event Source: Application Error
Event Category: None
Event ID: 1000
Date: 12/10/2015
Time: 8:16:12 AM
User: N/A
Computer: TEST-632A58B706
Description:
Faulting application macrocreator.exe, version 4.1.3.0, faulting module
macrocreator.exe, version 4.1.3.0, fault address 0x000948e7.

For more information, see Help and Support Center at
http://go.microsoft.com/fwlink/events.asp.
Data:
0000: 41 70 70 6c 69 63 61 74   Applicat
0008: 69 6f 6e 20 46 61 69 6c   ion Fail
0010: 75 72 65 20 20 6d 61 63   ure  mac
0018: 72 6f 63 72 65 61 74 6f   rocreato
0020: 72 2e 65 78 65 20 34 2e   r.exe 4.
0028: 31 2e 33 2e 30 20 69 6e   1.3.0 in
0030: 20 6d 61 63 72 6f 63 72    macrocr
0038: 65 61 74 6f 72 2e 65 78   eator.ex
0040: 65 20 34 2e 31 2e 33 2e   e 4.1.3.
0048: 30 20 61 74 20 6f 66 66   0 at off
0050: 73 65 74 20 30 30 30 39   set 0009
0058: 34 38 65 37 0d 0a         48e7..

**Comment by Pulover** [comment]
Thanks but unfortunately the hex address doesn't help me at all. There are numerous routines running in the background while the main window is active, and I haven't tested the app on winxp very much. It could be a dll access but there are too many, it's impossible to tell. Again, my best guess is the highlight function, because it keeps listening to a very active message from the listview (even with any painted rows). Did you try to disable it?

**Comment by comtech1234** [comment]
I didn't see that in the settings menu? I looked over it twice today and
didn't think I missed it. A lot of times it errors out on double click of
the shortcut.

On Thu, Dec 10, 2015 at 11:47 AM, Rodolfo U. Batista <
notifications@github.com> wrote:

> Thanks but unfortunately the hex address doesn't help me at all. There are
> numerous routines running in the background while the main window is
> active, and I haven't tested the app on winxp very much. It could be a dll
> access but there are too many, it's impossible to tell. Again, my best
> guess is the highlight function, because it keeps listening to a very
> active message from the listview (even with any painted rows). Did you try
> to disable it?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/Pulover/PuloversMacroCreator/issues/11#issuecomment-163683905
> .

##

**Comment by Pulover** [comment]
Sorry, it's not described as highlighting, it's in general > Show Colors & Help Marks for Loops and Statements. You can also disable it by clicking on the index color header.

**Comment by Pulover** [comment]
*Index column header.

**Comment by comtech1234** [comment]
I've disabled that and can still reproduce the error by loading the
program. I need to come to terms that it is probably an issue with my OS
and not your software. I was hoping it was an issue you could fix given the
circumstances of my operating system. So it's definitely not your fault.
I'm upgrading to windows 7 in a few weeks and this will no longer be an
issue. Thanks for your help Rodolfo.
