### ISSUE TITLE
Some small issues and suggestions.

### ISSUE THREAD

**Issue by chosen1ft** [Pulover/PuloversMacroCreator#111]
Good evening!

Issues:
1: Creat new project > add a new macro > set macro1's hotkey to 1 > set macro2's hotkey to 2 > close macro2. then the macro1's hotkey become 2, it suppose to be 1.

2: Creat new project > assign variable A =123(Expression On) > assign variable B = A - 3 (Expression On) > add a msgbox command to show variable B. then it output "-3" it suppose to be 120 . If I change "A - 3" to "A + 3" , then B output 126
 
3: When I export to ahk with the "Creat exe file" option ON,a warning show that "MPRESS.exe" not found. maybe not using the MPRESS.exe to compress exe by default will be better?

4: Creat new project > add a "If Statement" command > choose "compare variables" > variable textbox enter any name > choose contains > value textbox enter : 1,2,3 > click OK > edit the "If Statement" command again. then it become 1',2',3. and the third time edit it become 1'',2'',3. the forth time it become 1''',2''',3. and so on.

5: Creat new project > turn on "Preview Script" > add a "KeyWait" from "Run/File/String/Misc" > Enter any key > Click OK . then the Preview zone show nothing.If I edit the command again,It show the wrong interface.

Suggestions:
1: Can the global context sensitive hotkey be saved to project file? So those have different project files for different applications don't need to set the context sensitive hotkey each time they switch project files.

2: Can the "repeat""Delay""Insert Keystroke" toolbar be moved to the top side? I think it would be more efficient because most users coding on the upper half side of the main window.It take less mouse movement If the toobar at the top side. 

That's all, thanks for reading.

**Comment by Pulover** [comment]
> 1: Creat new project > add a new macro > set macro1's hotkey to 1 > set macro2's hotkey to 2 > close macro2. then the macro1's hotkey become 2, it suppose to be 1.
Good catch. Will fix that.

> 2: Creat new project > assign variable A =123(Expression On) > assign variable B = A - 3 (Expression On) > add a msgbox command to show variable B. then it output "-3" it suppose to be 120 . If I change "A - 3" to "A + 3" , then B output 126
Very weird bug. I'm going to investigate.

> 3: When I export to ahk with the "Creat exe file" option ON,a warning show that "MPRESS.exe" not found. maybe not using the MPRESS.exe to compress exe by default will be better?
Yeah, it's just a warning... but I guess I can add a check.

> 5: Creat new project > turn on "Preview Script" > add a "KeyWait" from "Run/File/String/Misc" > Enter any key > Click OK . then the Preview zone show nothing.If I edit the command again,It show the wrong interface.
Got it. Will fix it.

> 1: Can the global context sensitive hotkey be saved to project file? So those have different project files for different applications don't need to set the context sensitive hotkey each time they switch project files.
Yes, sure.

> 2: Can the "repeat""Delay""Insert Keystroke" toolbar be moved to the top side? I think it would be more efficient because most users coding on the upper half side of the main window.It take less mouse movement If the toobar at the top side.
Not sure I want to go through the trouble of adding another toolbar... but I'll think about it.

Thanks!

**Comment by chosen1ft** [comment]
Thanks for the reply.I have an idea about The Toolbar suggestion and I'm making a little tool for PMC. Today I found two more issues.

1: Creat new project > add a "mouse" command and just click "OK" > set delay to 777 from the delay toolbar(Not from the command) > open "Edit Macros" window and just click "OK". then the delay become 0 or the "Default mouse delay" value.

2: Creat new project > add a new macro > set macro1's hotkey to "1" > set macro2's hotkey to "Shift+1" > add two different command to each macro > play the "1" hot key. then it execute the commands from the"Shift+1". this happen on all 0-9 Number related hotkey.

**Comment by Pulover** [comment]
All the problems reported here should be fixed in v5.2.3. Thanks @chosen1ft .
