### ISSUE TITLE
App Freezes on start

### ISSUE THREAD

**Issue by lynxaegon** [Pulover/PuloversMacroCreator#113]
When the app starts, it freezes for a few seconds then if you click on anything it freezes again for a few seconds and it keeps going like that forever. 
OS: Windows 10 2004
I also have WSL2 enabled, but i don't think it matters because it's not a VM

**Comment by Pulover** [comment]
My guess is that it must be some anti-virus or other security program you have install that's performing checks. I can't test every possible scenario, I can only asure that it works normally for me on Windows 10.

**Comment by lynxaegon** [comment]
I don't have any antivirus, except the windows one which i can't disable (i tried.. and keep trying). Ok, so it's not a known issue, that's what i wanted to know.

**Comment by Pulover** [comment]
If it was just the freeze on startup I would say it's the update check. That's normal, and you can disable it on the help menu. But freezing on every click is not a known behavior to me.
