### ISSUE TITLE
Hotkey and Subtraction issues

### ISSUE THREAD

**Issue by chosen1ft** [Pulover/PuloversMacroCreator#116]
Greeting. 

1: Creat New Project > Set Macro1's hotkey to "1" > Set Macro1's hotkey to "None" > Add a new macro . Then Macro1's hotkey become "1" (Version 5.2.7)

2: I take some screenshot,Please take a look
![4](https://user-images.githubusercontent.com/69076802/95351324-ae57d900-08f3-11eb-9fee-7ea0439f7681.png)
![5](https://user-images.githubusercontent.com/69076802/95351337-b283f680-08f3-11eb-8fe3-c237e17e50e5.png)
![6](https://user-images.githubusercontent.com/69076802/95351339-b3b52380-08f3-11eb-9c8d-1dda5d686aa3.png)

**Comment by Pulover** [comment]
Oh, my... that substraction problem again. It's a bug in Uberi's ExprEval() but it's too complex to understand... I'll have to take another look at my Eval function. Thank you.

**Comment by chosen1ft** [comment]
Found another issue today, sorry for keeping you busy.

![1](https://user-images.githubusercontent.com/69076802/95471248-4c12dd00-09b4-11eb-82d3-8383cde4a71d.png)
![2](https://user-images.githubusercontent.com/69076802/95471254-50d79100-09b4-11eb-97d7-e4889b6dbcf6.png)
![3](https://user-images.githubusercontent.com/69076802/95471264-5208be00-09b4-11eb-9771-415d2c5c9a1e.png)

**Comment by Pulover** [comment]
Just released v5.2.8. @chosen1ft can you check and confirm that these problems are fixed, please? Thank you.

**Comment by chosen1ft** [comment]
All issues are fixed. It's the best birthday gift.Thank you very much.

**Comment by Pulover** [comment]
Thank you, and happy birthday!
