### ISSUE TITLE
Report some strange behavior.

### ISSUE THREAD

**Issue by chosen1ft** [Pulover/PuloversMacroCreator#119]
1:I upload a project file,it take almost 9 second to go back to the main window when I click "OK" from the "Edit Macros" window.
seems like the more macro tabs the more waiting time it takes.
.
.
.
2:The invisible macro tabs:(Still using my project file)
![1](https://user-images.githubusercontent.com/69076802/95756409-5563b880-0cd8-11eb-8159-3acd06f60f31.png)
.
.
.
.
.
3:This maybe not a big deal,but still a little strange:
![2](https://user-images.githubusercontent.com/69076802/95756915-036f6280-0cd9-11eb-8488-1bc4a7686dfb.png)
![3](https://user-images.githubusercontent.com/69076802/95756921-05d1bc80-0cd9-11eb-99a2-571923093359.png)
![4](https://user-images.githubusercontent.com/69076802/95756925-079b8000-0cd9-11eb-81db-2554a85c3a98.png)

[My Project File.zip](https://github.com/Pulover/PuloversMacroCreator/files/5365685/My.Project.File.zip)

**Comment by Pulover** [comment]
That's all Tab2 control's behavior and I cannot fix any of them. I tried to update it to Tab3, but it didn't show. I'll try again sometime, but I'm not even sure if it fixes these problems.
