### ISSUE TITLE
Add feature to remove / reduce extra pauses and mouse movements

### ISSUE THREAD

**Issue by SamHasler** [Pulover/PuloversMacroCreator#12]
Could a feature be added for removing extra pauses and mouse movements, to reduce a script down to it's necessary actions?

**Comment by Pulover** [comment]
Hi SamHasler,

Thanks for the suggestion, but this is not the place to make requests. You can send me an email to pulover@macrocreator.com.

Unfortunately I cannot parse the script to know which steps are necessary or not for everyone. You can, however, change Record Options and increase delay between recorded actions and remove actions you don't want, like mouse movements. Hope it helps.

Regards,
Rodolfo
