### ISSUE TITLE
VirusTotal Detects Malware For Portable and Installation editions

### ISSUE THREAD

**Issue by Grosner300** [Pulover/PuloversMacroCreator#120]
With version 5.2.8 VirtusTotal is showing executables containing malware.
Please consider addressing this scary issue.
![macrocreator-virustotal](https://user-images.githubusercontent.com/24656399/95903229-e16ef200-0d63-11eb-92a7-aec3a9731aaf.JPG)
![PuloverMacrocreator-Portable](https://user-images.githubusercontent.com/24656399/95903479-390d5d80-0d64-11eb-9c60-add071b876a2.JPG)
![MacroCreator-Setup](https://user-images.githubusercontent.com/24656399/95903755-96091380-0d64-11eb-8c05-d3efc1c3860d.JPG)

**Comment by Pulover** [comment]
[Report False-Positives To Anti-Virus Companies] (https://www.autohotkey.com/boards/viewtopic.php?f=17&t=62266)

As you can notice this is an open source project and there's positive no virus in the source code.

**Comment by Grosner300** [comment]
Thank you for reviewing this.

**Comment by Taizunz** [comment]
Most recent in-app update came packaged with Adaware Web Companion, so I can see why some anti-malware/AV apps pick up on this

**Comment by Tyrand** [comment]
Nice bundled adware bro
