### ISSUE TITLE
Version 5.2.8 Crashes When recording Control Key

### ISSUE THREAD

**Issue by Grosner300** [Pulover/PuloversMacroCreator#121]
While recording a macro, holding the control key for more than a couple of seconds, consistently crashes Macrocreator.
To reproduce:
1. Open Visual Studio Code (that is what i used for testing but issue exists with other applications).
2. Launch MacroCreator then Start recording (e.g. ^R->ok->F9)
3. In Visual Studio Code, highlight a text line (3 mouse clicks), and then press ^C  to copy the line
4. Move to new line  and press ^V to paste.
If you hold the control key down for a about a second then press the C or the V, the recorder will crash and the program crash / close. 

This seems to be a recurring issue for me.
I am using windows 10 Pro Insider Preview 2004 OS 20221.1000

**Comment by Pulover** [comment]
Just tried it here and it didn't crash. This was the recorded code:
```Send, {RControl Down}
Sleep, 9297
Send, {RControl Up}
Sleep, 343
Send, {RControl Down}
Sleep, 5985
Send, {RControl Up}

Is there any other possibly important information about your system that could be relevant? Do you have ahk scripts running? Did you try on a different computer? What's your keyboard language/layout?

**Comment by Grosner300** [comment]
I use the LControl button. Not that it should matter.
No other scripts are running.
English keyboard. Very standard stuff.

**Comment by Pulover** [comment]
I use VS too and after a few attempts it did crash, not with control key but when I pressed F9 to stop recording. That's because there's a shortcut for the AHK extension mapped to this key that runs the script in Debug mode. Not sure if this is the case for you, but maybe it could give you a hint. I changed the record hotkey to `ScrollLock` and it went well.

**Comment by Grosner300** [comment]
I agree. Changing record hotkey does address and prevent this issue. 
Thank you VERY MUCH for your assistance!
