### ISSUE TITLE
A complied exe that works fine output using v5.0.5. But doesn't work using v5.2.8

### ISSUE THREAD

**Issue by chosen1ft** [Pulover/PuloversMacroCreator#122]
Creat a new project and enter some command like the picture below:

![1](https://user-images.githubusercontent.com/69076802/95997959-eff20200-0e66-11eb-9802-f7baa77e27a0.png)

run it in pmc,it works fine on v5.0.5 and v5.2.8.
 
but create exe using v5.2.8,after pressing "Alt+D" , then the msgbox is not showing

then I check the output script files with compare tool,and this is the difference:
![2](https://user-images.githubusercontent.com/69076802/95999995-05682b80-0e69-11eb-8fbb-854e340c2509.png)

**Comment by Pulover** [comment]
> ### Version 5.2.3
> * Updated exported Compare variables from If Statements window to use expression.

You should use `"U"` now. I can't check right now, but maybe I forgot to add the "Use expressions" tip to this option.

**Comment by Pulover** [comment]
Indeed, the playback needs to be updated. Non-expression If-Statements are deprecated.

**Comment by chosen1ft** [comment]
I see. I used those commands to check if the hotkey is released.
Now with new version, I can set the hotkey to "!d Up::" to achieve that.Thanks.

**Comment by Pulover** [comment]
Updated Compare Variables feature in v5.2.9 to use expressions when the operator is a symbol.
