### ISSUE TITLE
Regarding the escape character in PMC

### ISSUE THREAD

**Issue by 10-veer** [Pulover/PuloversMacroCreator#123]
I'm not able to figure out which is the Escape Char in PMC. I came to know from the forums that ` the escape character in AHK, but I don't see that working in the PMC.

Image below contains all the combinations I have tried, but I don't see any of them working.
![image](https://user-images.githubusercontent.com/72913516/96097476-9c2afb80-0eee-11eb-85f0-5166e5ccc995.png)

I will rephrase the question again,

Suppose first is a variable, how can I display literally %first% in a messagebox, not the value stored in the variable first

(Basically I'm looking for this, because there is a URL link with multiple Percentage signs in it, and when I'm trying to run the URL link through PMC, it's all getting messed up)

**Comment by Pulover** [comment]
The escape char is indeed the backtick, but some times when I fix a problem, another one shows up 😛.
I'll take a look and try to fix it. Thank you.

**Comment by Pulover** [comment]
Should be fixed in v5.2.9, but if you have any other issue, feel free to reopen the it. Thanks.

**Comment by 10-veer** [comment]
Thanks man.
You are the best.
