### ISSUE TITLE
Common crash of the software during recording

### ISSUE THREAD

**Issue by monogiadown** [Pulover/PuloversMacroCreator#124]
I get a lot of times the following error on Windows 8 environment:

`<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
<System>
  <Provider Name="Application Error" /> 
  <EventID Qualifiers="0">1000</EventID> 
  <Level>2</Level> 
  <Task>100</Task> 
  <Keywords>0x80000000000000</Keywords> 
  <TimeCreated SystemTime="2020-10-15T12:13:47.000000000Z" /> 
  <EventRecordID>360142</EventRecordID> 
  <Channel>Application</Channel> 
  <Computer>MYPC</Computer> 
  <Security /> 
  </System><EventData>
  <Data>MacroCreator.exe</Data> 
  <Data>1.1.32.0</Data> 
  <Data>5dda0c13</Data> 
  <Data>MacroCreator.exe</Data> 
  <Data>1.1.32.0</Data> 
  <Data>5dda0c13</Data> 
  <Data>c0000005</Data> 
  <Data>0000000000040418</Data> 
  <Data>10e8</Data> 
  <Data>01d6a2ec132bebe8</Data> 
  <Data>C:\DEVELOP\MacroCreator\MacroCreator.exe</Data> 
  <Data>C:\DEVELOP\MacroCreator\MacroCreator.exe</Data> 
  <Data>e050d584-0edf-11eb-8151-005056b80584</Data> 
  <Data /> 
  <Data /> 
  </EventData>
  </Event>`

I use the Portable Version (x64).

Regards

**Comment by Pulover** [comment]
Thank you for the report, but it doesn't help much. Unfortunately, unless you can provide me a way to reproduce the issue (I'm using Windows 10, btw) I'm afraid I cannot try to fix it.

**Comment by monogiadown** [comment]
Hello @Pulover,
I have tested the x64 Portable version of your software (By the way, congratulations ... great work).
I have used it in both Windows 8 and Windows 10 and I get the same error.
I start the Recorder to get as many details as possible.
I click on multiple windows and I open and close various software (Browsers, MS Excel ...), at some point when I try to use the Keyboard ex. to Type in a form ... it crashes, producing the error I have shared with you, above.
I stop and resume the Recording and it seems also to affect (again crashes on keyboard buttons usage).

Also I have used the x86 Portable version and I got slightly different behavior.
The recording stops (not crashing) and it is producing a Message Box stating the error (again when I try to use the keyboard after clicking on various windows).

I don't know if that helps you.

Regards

**Comment by monogiadown** [comment]
Here is the Pop Up , error Message I get back
![error](https://user-images.githubusercontent.com/10660036/96248722-4d439b80-0fac-11eb-8a6e-d335ce724f61.PNG)

**Comment by monogiadown** [comment]
Hello again ... 

I found out that this error message is reproduced **Only** the **First** time you Type on the Keyboard the **dot (.)**  or the **backslash (/)** .
The first time you press the button (either . or /) the error message appears.
After that, it does not crash again (even if you type . or / ).

Regards

Fotis

**Comment by Pulover** [comment]
What's your keyboard layout/language?

**Comment by monogiadown** [comment]
My Keyboard, by default has English language, but it also supports Greek Keyboard (102 QWERTY keys).
The problem also appeared in a VM that has only English Language.
But is this relevant?
Even if it is not possible to get back the Key Code, can we create an exception handling not to crash?

Thank you

Regards

**Comment by Pulover** [comment]
I cannot know what are the equivalent of those keys on every keyboard layout, so I added a try statement to suppress the error message.
