### ISSUE TITLE
Truncation of array of strings during save 

### ISSUE THREAD

**Issue by ChRudy** [Pulover/PuloversMacroCreator#125]
It seems that a large array composed of strings =[ "xxxx","yyyy","zzzz",.....] > 200 long strings is saved with truncation, and play-back produces of course errors. Is it possible to solve such issue? (the turnover is for now to save in a text file the array [ "xxxx","yyyy","zzzz",.....]   and to regenerate the array by hand each time the project is open)

**Comment by Pulover** [comment]
This sounds like a limitation on the listview cell characters. PMC already has all of the data in objects, but there are still some legacy code from when it stored everything in the lists themselves. I can adjust that for a future release.

**Comment by ChRudy** [comment]
Hello, thank you for the fast response.  I understand the origin of the problem. What I do now as turnaround is BY HAND to open a text file, copy the full array with the PMC syntax and fill the array in the PMC code (while PMC is not running.
How to make that automatically (opening file, copy all is easy, but how to fill each array term with the coresponding term of the text file)?  Many thanks

**Comment by Pulover** [comment]
You could use the Push() method to concatenate more items into the array, thus splitting the long string into more rows.

**Comment by ChRudy** [comment]
Yes, I did it ... I was not thinking that such feature "ReadFileFeedArray" was already included (on the AHK command help, there is also StrSplit(), but this seems not being implemented in PMC...)
I did the following (maybe not the most optimised one) and it works fine for me. Thank you for the help.

ar := []
Loop, Read, E:\AllChronoFiles.txt
{
    ar.Push(A_LoopReadLine)
}
count := ar.Length()
MsgBox, 0, , %count%
indexF := 1
FileName := ar[indexF]
MsgBox, 0, , %FileName% and so on

**Comment by Pulover** [comment]
That's good enough. Just FYI StrSplit(), as well as all built-in ahk functions are available from the Function command window or inside expressions.
