### ISSUE TITLE
Image to Text OCR weakness: result may depends on  +-1 pixel 

### ISSUE THREAD

**Issue by ChRudy** [Pulover/PuloversMacroCreator#126]
It has been found that a single move (by only one pixel) may produce a wrong OCR result.  

In the attache bmp image, a figure explicitely equal to 9 is output by the OCR to a 8. It has been noticed that this wrong result depend on the position at +-1 pixel (as set in the PMC WinMove command by position X and Y). 

Moreover there are other cases: a 8 can become a 3 also with a sigle pixel move, etc...

This issue is maybe coming from the background which is not white TBC. If this is the case, a better contrast (or a trim of the gamma image) could improve the OCR reliability.

(For now a complex turnaround is used : image to text is used 4 times (after a WinMove by +-1 pixel) feeding 4 variables  and making complex comparisons  to detect the bad results)

[ImageOCR_9MayProduce8.zip](https://github.com/Pulover/PuloversMacroCreator/files/5393781/ImageOCR_9MayProduce8.zip)

**Comment by Pulover** [comment]
At  the moment OCR is done by [Vis2.ahk](https://github.com/iseahound/Vis2) which relies on [tesseract](https://github.com/tesseract-ocr/) so there isn't much I can do about it.

I plan to implement other options for OCR engine in a future version as some might work better than the current one.
