### ISSUE TITLE
If statements broken

### ISSUE THREAD

**Issue by jacobtriffo** [Pulover/PuloversMacroCreator#127]
Just updated to version 5.2.9 (x64) from the previous version and If statements that compare variables are broken.

I have a few large macros that are doing variable comparisons that determine if a goto happens or not, and the variable check appears to just always be true.

I tried a simple test macro, one variable, one goto, and it worked properly, but on my large 1000+ line macros they start failing partway through which of course leads to the macro doing all sorts of undesirable things.

The macros themselves have not changed in a month or so, I am 100% certain that the update is what's caused this issue.

**Comment by Pulover** [comment]
Indeed I made a mistake. Will release a fix in a while.

**Comment by Pulover** [comment]
Fixed in v5.3.0. If you run into other problems, please open a new issue. Thanks.
