### ISSUE TITLE
Image Search in borderless windowed mode is inconsistent

### ISSUE THREAD

**Issue by Mummified316** [Pulover/PuloversMacroCreator#129]
I've had no issues with Image Search in bordered windowed mode. But when I run it in borderless windowed mode it acts erratically. Sometimes it will find the image, sometimes it won't. That's about all I can say, borderless windowed mode just seems to cause major issues with it.

**Comment by Pulover** [comment]
You may want to try to change **Coord Mode** to `Client` in the Search options section of the Image Search window.

> Client [v1.1.05+]: Coordinates are relative to the active window's client area, which excludes the window's title bar, menu (if it has a standard one) and borders. Client coordinates are less dependent on OS version and theme.

https://www.autohotkey.com/docs/commands/CoordMode.htm

**Comment by Mummified316** [comment]
Setting the Coord Mode to either Client or Screen does not improve its ability to properly identify images. In fact, it actually makes things worse, in that, on the occasion that an image is properly identified, the coordinates outputted will be slightly off.

That being said, upon further investigation I have narrowed down my main issue. The problem seems to specifically occur if the image I am searching for was not onscreen when I activated the window. Here are some examples of when Image Search would work or not:

First example of Image Search working:
1. The image I am searching for is currently onscreen
2. I activate the window
3. The Image Search will properly identify the image

Example of Image Search not working:
1. The image I am searching for is currently _not_ onscreen
2. I activate the window
3. I do something that causes the image to show up
4. The Image Search will _not_ properly identify the image

Second example of Image Search working:
1. The image I am searching for is currently _not_ onscreen
2. I activate the window
3. I do something that causes the image to show up
4. I activate a separate window
5. I activate the main window again
6. The Image Search will properly identify the image

**Comment by Pulover** [comment]
You've solved the problem already.... ImageSearch requires that the window with the image to be active, so just use `WinActivate` before `ImageSearch`. This is not a bug with PMC, it's how the command works in AHK and a common issue to come across.
