### ISSUE TITLE
Failing to load large project files

### ISSUE THREAD

**Issue by Pulover** [Pulover/PuloversMacroCreator#13]
Reported by dammtools.

When opening a pmc file with a large macro (+4000 rows) the program hangs and the main window is not enabled again.

This seems to be thread issue and I'm already working on a solution. For now it's possible to work around the problem right-clicking on the tray icon and selecting "Deactivate Macros".

**Comment by vallorian** [comment]
Temporary fix : Load macro when Click RMB on Tray Icon and click Options and do it multiple times. Each times macro will load itself part by part :D

**Comment by Pulover** [comment]
Fixed in v5.0.1.
