### ISSUE TITLE
FileMoveDir doesn't work with %AppData%

### ISSUE THREAD

**Issue by Lucienest** [Pulover/PuloversMacroCreator#130]
When working with 

> FileMoveDir

 It works flawlessly between other Folders.
But when try to move any Folder to `%AppData%\Roaming\ ` directory it doesn't work at all,

A guess so _`%AppData%`_ requires admin privileges and I don't seem to find any option to grant.

**Comment by Pulover** [comment]
If you're running PMC as admin and still can't do it, I can only suggest you change your UAC settings. This is not something I can fix.
