### ISSUE TITLE
how to select WindowsForm10 Menu items?

### ISSUE THREAD

**Issue by bluefire81** [Pulover/PuloversMacroCreator#131]
![Menu](https://user-images.githubusercontent.com/72218157/96975782-a28b2a00-1523-11eb-8ddf-d841d72fcf5c.png)
how to select WindowsForm10.Window.8.app.0. Menu items and sub menu items?

**Comment by Pulover** [comment]
Not an issue or suggestion or directly related to the project. Please use AHK ask for help forum.
