### ISSUE TITLE
When entering an if statement it adds a control

### ISSUE THREAD

**Issue by mons3fa** [Pulover/PuloversMacroCreator#135]
When you add an If Statement it adds a random control to it.
![image](https://user-images.githubusercontent.com/73623066/97514486-0bbbd480-194c-11eb-9f95-c63c8996f89d.png)

I attempted to do this from scratch as well and still the same issue. It does not matter what type of If statement I write.

![image](https://user-images.githubusercontent.com/73623066/97514537-3312a180-194c-11eb-874e-9a68d86d88a5.png)

**Comment by Pulover** [comment]
This must be because of legacy code from previous versions, but you don't have to worry since this column is not considered for If Statements. I'm going to remove it in the next release.

**Comment by Pulover** [comment]
Fixed in v5.3.3.
