### ISSUE TITLE
Find/Replace issue

### ISSUE THREAD

**Issue by chosen1ft** [Pulover/PuloversMacroCreator#136]
![11](https://user-images.githubusercontent.com/69076802/97586871-b956e280-1a35-11eb-99d4-29d67a5afd8e.png)
![22](https://user-images.githubusercontent.com/69076802/97586884-bc51d300-1a35-11eb-86b6-e4adc508240a.png)
![33](https://user-images.githubusercontent.com/69076802/97586887-bcea6980-1a35-11eb-8488-0b4bbd272f8c.png)
![44](https://user-images.githubusercontent.com/69076802/97586889-bcea6980-1a35-11eb-8f42-708feacd23c9.png)

**Comment by Pulover** [comment]
Will fix that. Thanks!

**Comment by Pulover** [comment]
Fixed in v5.3.3.
