### ISSUE TITLE
Issue with files

### ISSUE THREAD

**Issue by SDWaps** [Pulover/PuloversMacroCreator#138]
How do i open the "Open files" popup in my code
This one ↓
![image](https://user-images.githubusercontent.com/47910472/97665481-3a11ef00-1ac7-11eb-946c-8d07a79a9d60.png)

**Comment by Pulover** [comment]
Type `FileSelectFile` in the search box.

https://www.autohotkey.com/docs/commands/FileSelectFile.htm
