### ISSUE TITLE
That Replace issue is not completely fixed

### ISSUE THREAD

**Issue by chosen1ft** [Pulover/PuloversMacroCreator#139]
in version 5.3.3. After clicking OK button. Macro2's text command stay with the right state, but macro1's not. its detail is still "111"
I think this issue affect all macro tabs. Becaues I replace it with "All Macros" option.
![111](https://user-images.githubusercontent.com/69076802/97729912-23db5180-1b0e-11eb-94d4-1f04cb842ed2.png)
![222](https://user-images.githubusercontent.com/69076802/97729930-29d13280-1b0e-11eb-825f-a03301088ac5.png)

**Comment by Pulover** [comment]
I didn't remember you could replace results in all macros... will leave this one unfixed for now, unless some more critical issue is found.

**Comment by Pulover** [comment]
Yes, hopefully. As long as I successfully implement most of the features in my list I'll be able to name it so.

I've been struggling to implement the first one, which is a TreeView alternative for the ListView of actions. Some commits are already in the Dev branch.

**Comment by Pulover** [comment]
Fixed in v5.3.4.
