### ISSUE TITLE
Error exporting to exe (OCR)

### ISSUE THREAD

**Issue by keklok** [Pulover/PuloversMacroCreator#140]
![image](https://user-images.githubusercontent.com/71589796/97793145-13ec6c00-1bf9-11eb-8570-3a8f4ea128ca.png)
what should I do.
Thanks for answer!

**Comment by Pulover** [comment]
Open the exported *.ahk file in a text editor and you'll see the url of the vis function close to the end (you can look it up here in github as well). Download vis.ahk and save it to a Lib folder in the same folder of the ahk, then export it to exe again.
