### ISSUE TITLE
[Feature request] Image search Batch

### ISSUE THREAD

**Issue by flozi00** [Pulover/PuloversMacroCreator#141]
Sometimes the tool does not find the Icon it should click, so I just make an loop in native AHK.
Would it make sense to integrate such an loop that iterates over an folder of these images of the object ?

**Comment by Pulover** [comment]
> Sometimes the tool does not find the Icon it should click, so I just make an loop in native AHK.

I don't understand what you mean. You can create a loop to iterate through a folder in PMC too.

**Comment by flozi00** [comment]
I mean just pointing to the directory instead of the specific image file in pmc.
That pmc creates this loop automatically

**Comment by Pulover** [comment]
I don't think it makes sense to add this feature when you can simply use the LoopFile command and place the variable in the ImageSearch file field.
