### ISSUE TITLE
Randomly stops responding to user input

### ISSUE THREAD

**Issue by Varriount** [Pulover/PuloversMacroCreator#142]
Recording via F9 causes Macro Creator to no longer respond to any input from the user. The program itself is still running (it responds to window messages and can be minimized/expanded) however button clicks, attempting to exit the program, etc. do nothing. When this occurs the program must be closed via the task manager.

This problem also occurs randomly while performing other edit functions, although I can't reliably reproduce those conditions.

If there's any other information you need, please let me know.

**Comment by Pulover** [comment]
Thanks for the info, but what I need is exactly a consistent way to reproduce the problem.
