### ISSUE TITLE
Changes Not Applied Bug

### ISSUE THREAD

**Issue by TheChrisOwl** [Pulover/PuloversMacroCreator#143]
I have this bug where I make a change to the program and click ok and about 20% of the time the change doesn't take effect.

Example: I click the messagebox icon, I type the message, I click ok. The message box does not show up.
Example: I edit an existing messagebox, I edit the message, I click ok. The message box still shows original message.
Example: I edit a variable in the image finder (perhaps I change FoundX and FoundY to something else). I click ok. It does not update the variable names.

This problem has gotten so bad that I save the longest variable name or text on my clipboard before clicking ok every time now to save myself from typing the same thing again.

**Comment by Pulover** [comment]
I can't seem to reproduce this problem. Can you make a video showing it happening?

**Comment by TheChrisOwl** [comment]
Here is an example, I can film more too. After I closed the program and reopened it the problems went away for a while.
https://www.dropbox.com/s/g1xwkt6fh3v447y/Videoleap-DC8960C8-C9D1-450C-970B-B4223276A133.MOV?dl=0

I am starting to think a few of my issues are the same issue.

The issue:
After using a large program for a while (creating new lines, editing lines, testing all or part of program) (30 tabs, with many 300+ lines of code), the program interface stops functioning correctly. 

Some of the errors include:
- Changes not saving
- Dragged macros not moving correctly
- Code not executing correctly when tested

Workaround:
- Save constantly
- When my code stops working randomly, save and close PMC and reopen to see if it works now.

**Comment by Pulover** [comment]
I've watched the videos and tried it here many many times but it just won't happen. Unless you or someone else is able to point the specific settings or situation that causes the problem I don't know what I could do to fix it.
