### ISSUE TITLE
Cannot find image bug

### ISSUE THREAD

**Issue by TheChrisOwl** [Pulover/PuloversMacroCreator#144]
Problem Setup:
1) I open notepad and type something via code
2) I click 'x' via image search
3) I click 'don't save' via image search

Issue:
Step 3 will not execute. It does not find the 'don't save' image. I think this is because it is in a dialogue box. However, I have changed the 'Coord' dropmenu items to all three options (Window, Screen, Client) and still it cannot find the 'don't save' button. Is there no way for me to ImageSearch just what I see on the screen? Like whatever windows are 'on top'.

Note:
The problem also happens on instagram website. If I want to click the heart button on an image (since the image always pops up in something like a pop-up box). The program will not consistently find the heart. My theory is that it is searching the page below the pop-up.

**Comment by Pulover** [comment]
ImageSearch issues are not directly related to PMC, but with how the command works in AHK. Make sure the window is active using WinActivate before searching and try to use some variation in the command settings.
