### ISSUE TITLE
Dragged Tabs Swapped Content

### ISSUE THREAD

**Issue by TheChrisOwl** [Pulover/PuloversMacroCreator#145]
Problem Setup:
1) Have many tabs of code open (like I have 30 tabs) many of them with 300+ lines of code
2) Drag one from the far side to the near the front

Issue:
Sometimes (maybe 10% chance) it moves the name of a nearby tab instead of the selected one and the content gets moved around in some way.

Example:
Macro25 is moved beside Macro2 and Macro3. I notice that Macro24 moved instead of Macro25 and has the content of Macro25. When I check Macro25, it also has the content of Macro25. The content of Macro24 is deleted. Ctrl-Z does not undo this error. I need to close down and not save the program now. 

Notes:
- So far I have solved this by saving the program before I move any tabs around.

**Comment by Pulover** [comment]
Again I'm not able to reproduce it, so if you can make a video showing it, maybe it will help me investigate.
