### ISSUE TITLE
GoSub Error

### ISSUE THREAD

**Issue by TheChrisOwl** [Pulover/PuloversMacroCreator#146]
Problem Setup:
1) Use program for over an hour playing the macro every once in a while. Over 30 macro tabs many with 300+ lines of code.
2) Use 'Play Selected Rows' button with one of the rows being a 'GoSub' function.

Issue:
The GoSub will refuse to execute sometimes. When that happens, I would comment out all the content of the macro that GoSub points to and instead I would only put one message box which says 'success'. The message box would not show.

Solution:
1) So far I have to solve this by either closing down the program and reopening or even restarting my computer a few times if the first option didn't work. After this, the program would work.
2) If I play the entire page which contains the 'GoSub', it would execute correctly. This makes my testing take a long time though.

**Comment by Pulover** [comment]
This is not a scenario I can test only with your description. I need test code that I can use to reproduce the problem.
