### ISSUE TITLE
Error when updating

### ISSUE THREAD

**Issue by askaaron54** [Pulover/PuloversMacroCreator#147]
I tried to update the software today and after the update, I received the following message:

Error: Parameter #3 must not be blank in this case.

Line#
16506: Menu,PreviewMenu.(AutoReach)? "Check":
"Uncheck:",%Lang031%

The current thread will exit.

And then it shuts itself off. I tried to uninstall and re-install in a new location, but it's still giving me the same error.

Any ideas?

Thanks!

**Comment by Pulover** [comment]
There's no AutoReach variable in my code and that's weird. Anyway, check this issue #108. There's also a portable version available.
