### ISSUE TITLE
4K display issues

### ISSUE THREAD

**Issue by selsie** [Pulover/PuloversMacroCreator#150]
I just started the software for the first time, and found that the icons etc are difficult to use with a 4k display.
Just to show you how it looks on my screen, keeping Firefox as background to illustrate the difference in the UI.

![grafik](https://user-images.githubusercontent.com/15048308/102698489-05f0ba00-423e-11eb-8388-0327afb7b044.png)

https://docs.microsoft.com/en-us/windows/win32/hidpi/high-dpi-desktop-application-development-on-windows is pointing in the right direction to fix it (I think), but I'm not a real programmer, so I don't know much.

**Comment by Pulover** [comment]
You can change icons and main font sizes in the View menu.

**Comment by selsie** [comment]
Yes, but still the UI elements don't fit. There are some overflow issues
even when using the DPI compatibility settings. Have a look at the
screenshot I included.

Thanks for your speedy answer.

**Comment by Pulover** [comment]
I see but honestly I have no intention of fixing that. Sorry.
