### ISSUE TITLE
Error with the tabulation in the message boxes

### ISSUE THREAD

**Issue by TirOFlanc** [Pulover/PuloversMacroCreator#151]
Hi Pulover !

Thank you very much for taking over the development of 'Macro Creator'.

It's all in the title and on the screenshots.

![image](https://user-images.githubusercontent.com/56934692/102787527-811eb100-43a1-11eb-94b6-35cedab9b9b0.png)
![image](https://user-images.githubusercontent.com/56934692/102787372-461c7d80-43a1-11eb-9cff-c5280ec43a2f.png)

There was no such error under version 5.0.5, and it seems to be due to indentation depending on whether 'spaces' or 'tabs' are used.

v5.0.5 :
![image](https://user-images.githubusercontent.com/56934692/102788744-68af9600-43a3-11eb-8282-836bf7efb708.png)

v5.3.7 :
![image](https://user-images.githubusercontent.com/56934692/102789134-01461600-43a4-11eb-9264-07d09f0ede6a.png)

Ask if you need more information.
Have a good day.

**Comment by TirOFlanc** [comment]
Another error related to the tabulations, but regarding the variable assignment.

![ErrorTabNPipe](https://user-images.githubusercontent.com/56934692/102791285-12dced00-43a7-11eb-9404-767fdf7dee38.PNG)

This has the consequence of replacing the 'Tabs' by 'Pipes' and thus shifting the columns in the 'pmc' file.

**Comment by TirOFlanc** [comment]
A solution would be to replace the tabs by the variable 'A_Tab' when saving the 'pmc' file or to indicate with a warning message that it is not advisable to use the tabulation at the risk of corrupting the file.

**Comment by Pulover** [comment]
I don't see any issue with tabs in MsgBox. Neither with A_Tab variable nor with tab character.

Btw, I haven't taken over the development. I'm the original developer.

**Comment by TirOFlanc** [comment]
> I don't see any issue with tabs in MsgBox. Neither with A_Tab variable nor with tab character.

This is however highlighted on the first two screenshots on lines 14 and 23, line 14 being a rewrite of line 23 but without tabs in the message box.

![image](https://user-images.githubusercontent.com/56934692/102816856-fbb1f580-43ce-11eb-8572-154ada3107fc.png)
![image](https://user-images.githubusercontent.com/56934692/102817000-3ae04680-43cf-11eb-99d7-d89dcf85f8eb.png)

> Btw, I haven't taken over the development. I'm the original developer.

Yes, I know, it's a translation problem. I mean I'm glad you're updating it after 4 years of absence.

**Comment by TirOFlanc** [comment]
Oooh !

Tab is ![image](https://user-images.githubusercontent.com/56934692/102817348-ebe6e100-43cf-11eb-80b9-e79c48af7975.png)

**Comment by Pulover** [comment]
I still don't know what you're talking about...

**Comment by TirOFlanc** [comment]
The problem is that when saving, Tabs have been replaced by Pipes which are used to delimit the columns in the 'pmc' file.

![image](https://user-images.githubusercontent.com/56934692/102827686-535a5c00-43e3-11eb-8cea-929398a16128.png)

**Comment by Pulover** [comment]
I saved a file with tabs here and it loaded normally.

**Comment by TirOFlanc** [comment]
Maybe by upgrading from version 5.0.5 to 5.3.7 ... or by saving and closing the application too quickly.

I'll let you know if I have any news about this problem, in the meantime I've fixed my file by hand, if you think it's ok, you can close this post ...

And have a good night ! ;)

**Comment by TirOFlanc** [comment]
Hmm, Have you tried with a MsgBox in an if condition?

**Comment by TirOFlanc** [comment]
![image](https://user-images.githubusercontent.com/56934692/102828622-6cfca300-43e5-11eb-8ef8-bc08e0f0dd44.png)

**Comment by Pulover** [comment]
You have to give me a consistent way to reproduce the problem. Otherwise I'll just have to close the issue.

**Comment by TirOFlanc** [comment]
Ok, I'll let you know if I have any news about this problem. ;)

Thank you for your patience.
