### ISSUE TITLE
Disappeare

### ISSUE THREAD

**Issue by techcom78** [Pulover/PuloversMacroCreator#154]
I have downloaded the file Macro-Creator-setup.exe and then tried to install it and the file just vanished. I then downloaded the file two more time and excatly the same situation occured.

**Comment by TirOFlanc** [comment]
I invite you to read requests similar to yours for more information.

> https://github.com/Pulover/PuloversMacroCreator/issues?q=virus

**Comment by Pulover** [comment]
Duplicate #112
