### ISSUE TITLE
[enhancement] LoopParse and escape character

### ISSUE THREAD

**Issue by TirOFlanc** [Pulover/PuloversMacroCreator#156]
Hi,

It's up to you to see if it's a good idea, but I encountered a problem with at least one delimiter character in a LoopParse command (the semicolon) and I thought it might be a good idea to add the escape character automatically when the user doesn't do it.

![image](https://user-images.githubusercontent.com/56934692/104090433-0269b500-5277-11eb-966a-0a6a5a6bce1f.png)
![image](https://user-images.githubusercontent.com/56934692/104090453-2cbb7280-5277-11eb-8836-a9f61ef31dd7.png)

![image](https://user-images.githubusercontent.com/56934692/104090458-3b098e80-5277-11eb-9d25-71ccd00ea302.png)
![image](https://user-images.githubusercontent.com/56934692/104090461-452b8d00-5277-11eb-9c64-6f4d8c720519.png)

Otherwise, it doesn't matter, just be aware of it.

Have a nice day.

**Comment by Pulover** [comment]
Implemented in v5.4.0. Thanks.
