### ISSUE TITLE
Cannot select screenshot area through Anydesk

### ISSUE THREAD

**Issue by leodoi3** [Pulover/PuloversMacroCreator#157]
I am using the program through Anydesk. When using Image/Pixel search, clicked on 'Make screenshot' button. And where it ask to select an area, I am unable to do so.  I can only right-click but I can't drag.

**Comment by Pulover** [comment]
Go to Options and select "Press Enter to capture" then you can use Ctrl+Arrows and Shift+Arrows to move and resize the rectangle.

**Comment by leodoi3** [comment]
That works but when doing it on a large screen resolution the whole process is tedious, especially if I have to do many of these.

**Comment by Pulover** [comment]
I know but that's the only solution I can offer. I cannot fix every problem with every possible remote access software. Why don't you use the system's built-in snapshot tool or some other software for that?

**Comment by Pulover** [comment]
Have you tried to change the capture button to left or middle?

**Comment by leodoi3** [comment]
> 
> 
> Have you tried to change the capture button to left or middle?

Yes and neither of them worked.
