### ISSUE TITLE
Importing a default(ex. Macro15) name messes up other macros

### ISSUE THREAD

**Issue by hunts02** [Pulover/PuloversMacroCreator#158]
I noticed a bug whenever I export a default named macro(ex.Macro15) and then import it to another project with a renamed (Macro15 renamed to Main for ex.) macro. It messes up either the end of the macro, if I have several tabs up to 20 or the renamed Macro15. Ive been having this issue ever since. anyone else have this issue?
What I mean by mess up its  either missing lines or duplicated content in tab etc.

**Comment by Pulover** [comment]
Thanks for reporting this problem. Fixed in v5.4.0.
