### ISSUE TITLE
Win 10 Def claims virus

### ISSUE THREAD

**Issue by ran88dom99** [Pulover/PuloversMacroCreator#16]
Windows 10 defender claims a virus is inside portable x86 executable from the main site.

**Comment by ran88dom99** [comment]
[PuloversMacroCreator-Portable.zip](https://github.com/Pulover/PuloversMacroCreator/files/230683/PuloversMacroCreator-Portable.zip)

**Comment by Pulover** [comment]
As you can see this project is open source. You can even download the source and compile it yourself, so it's a false positive.

It would help if people would submit the file as a false positive when this happens. This is the link to report for Windows Defender: https://www.microsoft.com/en-us/security/portal/submission/submit.aspx

**Comment by ran88dom99** [comment]
Running Compile.ahk warns of INI file missing.

**Comment by Pulover** [comment]
Please, read the **Compile Instructions** in the **ReadMe** file.
