### ISSUE TITLE
Having problems with some applications

### ISSUE THREAD

**Issue by lex-nova** [Pulover/PuloversMacroCreator#160]
When I right click inside the emulator(bandicam too), it won't proceed to the next step.
And when I try to record actions inside the emulator, the macro recorded is unusable, moving to wrong places, etc.
Then I tried the Screen CoordMode, and different SendMode, this time the movement is correct, but there's no mouse click observed, also keyboard input are not recorded for some reason.
https://user-images.githubusercontent.com/45550156/106382445-ffd82680-6402-11eb-8e52-6fad1c97a960.mp4
(it's an phone emulator application)

**Comment by Pulover** [comment]
You can try to change SendMode in settings to Play but it might be just not possible to make it work on some applications.
