### ISSUE TITLE
Playback speed doesn't deselect after selecting another option

### ISSUE THREAD

**Issue by JohnathanN28** [Pulover/PuloversMacroCreator#161]
![Screenshot 2021-02-01 222010](https://user-images.githubusercontent.com/78399047/106551819-aa237d00-64db-11eb-8ebe-c7ac6e5526f8.JPG)

**Comment by JohnathanN28** [comment]
I tried resetting to default settings: didn't work

**Comment by Pulover** [comment]
Thanks for reporting it. I'm going to fix it but since it's not a critical issue I'm going to postpone it until I have something else to update.

**Comment by JohnathanN28** [comment]
> Thanks for reporting it. I'm going to fix it but since it's not a critical issue I'm going to postpone it until I have something else to update.

Thanks, man! I appreciate your program very much.
