### ISSUE TITLE
Incorrect coordinate on Image Search  results

### ISSUE THREAD

**Issue by Aggie1985** [Pulover/PuloversMacroCreator#162]
Image search is not selecting mid coordinates when said image is found. Tried new search coordinates and images and still goes to an incorrect location.

Using 5.4 builds, tired both 64 and 32 versions. Toggled on and off adjust to center of image and nothing changes. It was working fine two days ago and not it's not. I know I had an MS update so that may have been the cause of the change. Sys Win 10 Pro 64bit, ver 20H2, build 19042.789, Experience pack 120.2212.551.0

**Comment by Pulover** [comment]
You might want to check coordmode in the ImageSearch command window. If you want it set to window, you should use WinActivate prior to the ImageSearch.

**Comment by Aggie1985** [comment]
I have the image search coordmode set to screen, however, after your comment, I went back to check default settings and it was set to window and I changed it back to screen and things worked as they should... Thanks for the quick reply and great tool btw, thanks for all your time and effort on this tool it's great.
