### ISSUE TITLE
Stopping & Starting a Macro during a Pause does not reset.

### ISSUE THREAD

**Issue by psultan** [Pulover/PuloversMacroCreator#165]
Make a macro with a 1 minute pause.

1. Play the macro.
2. Stop the macro with the shortcut key or controls toolbar during the pause.  (The pause icon resets to the play icon indicating the macro has stopped)
3. Play the macro again (**before** the 1 minute pause completes)

Current Behavior
- The macro continues the last position (the pause completes, and the macro continues)

Desired Behavior
- The macro resets and starts from the beginning. 

&nbsp;

My macro has several 5 minute pause.  When I notice it is not running properly during the pause I am unable to restart it.  My current workarounds are:

- Close Macro Creator and restart the macro.
- Wait for the 5 minutes to complete and hit stop again.
- Create a Message Box with a settimout for every significant pause.  

However, since pause is such an ubiquitous command, since it is auto-generated, it may be good to figure out how to terminate it from a stop.

**Comment by Pulover** [comment]
Thanks for the report, but this is a limitation on AutoHotkey that I can't seem to overcome. In fact I got a different behavior: the macro does start from the beginning but only AFTER the pause time has passed. That's because I cannot interrupt the `Sleep` command thread after it has been called. You might of putting the Sleep command inside a loop, but it loses precision.

**Comment by psultan** [comment]
Using a loop with a small sleep is a very good idea.  Doing this, or using the Message Box, are definitely the best solutions.

This clip demonstrates hitting Stop & Play during a Pause does not stop the first run.  This was very confusing the first few times it happened.  

1. I start the macro.
2. I hit Stop when the macro is Paused on line 10
3. I hit Play when the macro is still in the Pause timer.   
4. After ~10 seconds the macro continues on line 11 from the first pass.  (I expect this pass to stop and reset to 0)
5. The macro then starts a new second pass from 0.

https://user-images.githubusercontent.com/1406954/109038744-0e300000-769a-11eb-9cb3-8065dc9e013a.mp4

It makes more sense now knowing you cannot interrupt AHK's sleep command.  I was not considering the AHK translation and was just using your tool as a standalone application.  Now that I am aware of the behavior I can work around it.

**Comment by vdurante** [comment]
@Pulover cant we start ahk on a separate process or thread and then just kill it? I have several 5mins+ pauses and they just freeze the whole program for several minutes unless I restart it
