### ISSUE TITLE
"Setting Request" to "stop minimizing application" on RUN

### ISSUE THREAD

**Issue by renehasp** [Pulover/PuloversMacroCreator#167]
Hi is there any way to add a setting option to stop minimizing the application when I hit the RUN button. I have 2 monitors and I have PMC on my left and on my right monitor the macro runs and when I test it's always so frustrating having to maximize the PMC after it gets minimized. 

It gets me out of my work flow. But I also understand the point of the minimize on run. I'm just asking if there is anyway to add a togle setting for that feature. So I can turn it off or on as needed.

**Comment by Pulover** [comment]
You can check the hotkeys always enabled option in the options menu.
