### ISSUE TITLE
Edit "KeyStroke"

### ISSUE THREAD

**Issue by renehasp** [Pulover/PuloversMacroCreator#168]
Not sure if this is a bug or not. But I can't figure out how to edit an existing "Key Stroke"  

![image](https://user-images.githubusercontent.com/7088310/109246887-09aa3b00-77b1-11eb-87ac-2105e1fd8956.png)

I insert a new Key Stroke I get this. 

![image](https://user-images.githubusercontent.com/7088310/109247051-424a1480-77b1-11eb-877d-b49eba63597d.png)

I would expect the same to pop up when I'm editing. But instead I get this..
![image](https://user-images.githubusercontent.com/7088310/109247109-57bf3e80-77b1-11eb-8469-cd7e7d235d5f.png)

and in that window I can not change the send key.

Workaround is to delete the existing line and create a new Send Key..  Not sure if this is by design or a bug.

**Comment by Pulover** [comment]
It's by design. The keystroke edit window is used mainly for setting control. You can replace them like you said or you can use the find and replace window.
