### ISSUE TITLE
Remove "fading" animation when deleting commands form list

### ISSUE THREAD

**Issue by debuglevel** [Pulover/PuloversMacroCreator#173]
I just recorded a macro and wanted to remove 50 pause/mouse movement combinations. So i selected all those entries and hit [del]. But it seems that there is some animation when a list entry is removed, which is applied on every item you remove on a selection. If therefore took about 30 seconds to delete those list entries. My recommendation is to remove this animation or at least disable it when multiple items are deleted.

**Comment by Pulover** [comment]
There's no animation. It's just how it works in AHK, it must remove one row at a time in a loop. It's slow I know but I could never find a faster reliable way.
