### ISSUE TITLE
Image Search Move To Center Bug

### ISSUE THREAD

**Issue by vqt123** [Pulover/PuloversMacroCreator#175]
Adjust to center of image does not work when using Coordinate mode: SCREEN

I have a 3 monitor setup. When using a side monitor, adjusting to center of image does not give the correct coordinates.

**Comment by Pulover** [comment]
Yes, it's working. You must set both Mouse coordmode (Options > Settings > Defaults) and Pixel coordmode (Image/Pixel Search window) to SCREEN.
