### ISSUE TITLE
CPU Usage doing nothing

### ISSUE THREAD

**Issue by TheOne010** [Pulover/PuloversMacroCreator#178]
For some reason MacroCreator.exe uses a fair bit of CPU (10-15%) doing nothing.  If a dropdown or context menu is open the load drops to 0,xx%. I have tested 5.4.0 both x64/x86 versions on Windows 10.

**Comment by TheOne010** [comment]
Never heard of an application that uses this much only to listen to events, its also weird that it drops to 0,xx% if a dropdown menu is open. It just seems uneccessary causing the CPU fan to speed up, draw more power etc. for just waiting for a key press or something. Is there a way to disable some of these functions?

**Comment by TheOne010** [comment]
Ok, i have tested this on another machine and it's not an issue there either. I'll check back if I find out what causes this (if its not an issue with another application). Thank you very much for your support.

**Comment by Freekmine** [comment]
I am having the same issue. To the extent that it consistently takes 45 seconds for the PMC Settings dialog to open after clicking Options>Settings.

**Comment by SullieLore** [comment]
This also seems to be happening to me. The program will start by using 0-2% CPU, then spike to 10%+ after 30 or so minutes of editing a script. Multiple scripts tested. Restarting the program doesn't reset the CPU below 10%, but restarting the PC does fix the problem until it starts again around 30 minutes later. Would be great to have a fix, as the program is basically unusable at such high CPU spikes; becomes unresponsive to most UI clicks etc.

**Comment by faxmbo** [comment]
I also encountered the exact same problem
