### ISSUE TITLE
Save As

### ISSUE THREAD

**Issue by user3247548** [Pulover/PuloversMacroCreator#18]
I try to use Save As (button or menu)
The command apparently finishes but the new file is not created.

The new file name appears under recent files, but If I want to use that link the next day I get 
"Error the file was not found"

**Comment by Pulover** [comment]
Hi,
Thanks for reporting. I had already identified and fixed this problem. It will be corrected in the upcoming release.

**Comment by Pulover** [comment]
Fixed in v5.0.1.
