### ISSUE TITLE
PMC unresponsive odd issue

### ISSUE THREAD

**Issue by classicus1** [Pulover/PuloversMacroCreator#180]
First off, I want to say thank you for this awesome app. I don't mind going the AHK route, but PMC just saves me a whole lot of time and I'm often making complicated scripts that would further add to the time it'd take me with AHK. Thank you!!!

I'm having an odd issue that I'll try my best to explain. When this issue starts to occur, the only fix seems to be a reboot of my PC, which is a temporary fix. From what I have observed, it only begins to occur after my PC has not been rebooted for 2+ days. 

When I open PMC, the program opens up. If I hover my mouse icon over any of the icons, I see the blue highlight and the tooltip pop up. But clicking on any icon does nothing. I can click on the dropdowns up on to the title bar (File, Options, Help, etc...), but clicking anything in the dropdown does nothing. If I try to close the program with the red X on top right, it does nothing (minimize and resize icons work though). I have to open Task Manager to force close the program. 

Another thing to note is that the Tips window which opens when the program starts, will not open when the issue decides to start occurring. This is one quick way I know that PMC will no longer work until I reboot.

Things I've tried:
-Deleting %AppData%\MacroCreator
-Full uninstall and install (to include removing registry entries for PMC after uninstall)
-x64 and x86 versions, with/without appdata option
-Installing latest (and earlier versions) of PMC
-Installing latest version of AHK
-Ending just about every process on my PC via Task manager other than Windows core services
-Running PC for 2+ days without sleep (or with sleeping overnight)
-Keeping PMC open for 2+ days to see if it'll keep behaving correctly if I keep it open
-Checking Event log for any errors (there were none)
-Running few "Windows 10" repair commands, sfc scan, all were clean
-Scouring the issues threads, open and closed, to see if I could find anyone experiencing the same issue but not much luck here

None of the above have worked to resolve the issue. Once it decides to occur, it will always happen no matter what I try. Only a reboot will get it working smoothly again (temporary). I also have PMC on a laptop and the issue does not happen there at all, so I'm not sure it could be reproduced. 

I'm at wits end here. If you got any tools or ideas I can use to further troubleshoot and try to isolate the issue, I'd be happy to keep digging. My only other guess is I've noticed one of my services clogs up the event log pretty badly, and it gets to a point that some events might not get recorded properly anymore until I reboot. I am going to start another test by rebooting and stopping that service as soon as Windows loads. I don't see how this might affect PMC, but I will test and see.

**Comment by Pulover** [comment]
This is not related to PMC itself, it's an issue with your system, so I can't help. You'll have to find out what's causing it or maybe reinstall Windows.

**Comment by classicus1** [comment]
Thanks for the reply Pulover, I also suspect some issue within the system somewhere. Although I would expect more apps to misbehave in this case. But as far as I can tell, only PMC does. I was wondering if PMC interacts with Windows in some way that other apps do not. Last resort would be to reinstall Windows. I will try a few more things first to see if it has any result, if I find something I'll leave it in the comment in case it might benefit anyone else.

**Comment by classicus1** [comment]
@Pulover Well, turns out my last test was the culprit. It was an issue with mpservice.exe from CoolerMaster (I have one of their CPU fans). They make several products that call on mpservice.exe, so if anyone else reports a similar issue as I was getting, this is something to check for. It will be listed as "CoolerMaster MasterPlus Technology Service" in services.msc. It should be stopped from here (ending process via task manager will cause it to start back up). The service can just be set to Manual or Disabled in case anyone else runs into this issue, although they'll lose some of the app functionality for their CoolerMaster product. In my case it's not an issue.

**Comment by GForceWeb** [comment]
@classicus1 I'm getting identical behaviour to what you've described (I've only just installed PMC and am trying to use it for the first time).

I don't have any CoolerMaster Products nor do I have mpservice.exe running so something else is likely conflicting with PMC and causing the same behaviour but I don't have any clue as to what that might be at this stage.
