### ISSUE TITLE
Is there a way to uninstall?

### ISSUE THREAD

**Issue by bob448** [Pulover/PuloversMacroCreator#186]
There's no uninstall .exe in the folder, no uninstall entry in the add and remove programs, the "Uninstall pulover's macro creator just brings me to This PC, what do I do?

**Comment by kapitanluffy** [comment]
Were you able to uninstall it?

**Comment by bob448** [comment]
Yes, it was not showing uninstall because i installed it with "Don't use appdata" setting.
