### ISSUE TITLE
[Question] How does the floating toolbar work?

### ISSUE THREAD

**Issue by sunny-lan** [Pulover/PuloversMacroCreator#189]
I noticed when I use the tool clicking buttons on the floating toolbar doesn't cause other windows to lose focus, including fullscreen 3D applications. How did you achieve this? I can't seem to figure out the right flags.

**Comment by Pulover** [comment]
The flag you need is _+E0x08000000_:

`Gui, +AlwaysOntop +E0x08000000`

**Comment by sunny-lan** [comment]
Thanks. Do you know how to (if possible) for this window to have a textbox (receive key input, but only if the textbox has focus)?

**Comment by Pulover** [comment]
Now that's a question for the AutoHotkey forum.
