### ISSUE TITLE
Suggestion: Hotkey to open main window

### ISSUE THREAD

**Issue by nldev** [Pulover/PuloversMacroCreator#191]
Would love to be able to press a hotkey to open the main window, or be able to toggle it from open-to-tray. Just wish it were a bit easier to manage macros and assign play hotkeys without having to go to the tray every time. Alternatively, it would also work if opening the program again caused it to open from tray (currently attempting to open the program while its in the tray does nothing).

I just started using PMC, but I mainly want to be able to quickly create temporary macros and assign them to the same set of hotkeys pretty much every time. There may be some existing settings/functionality I'm overlooking however.

Thanks for this application by the way! Really great stuff. ❤

**Comment by Pulover** [comment]
The program doesn't have such global hotkeys to avoid conflict with user-defined hotkeys, but you can create one yourself. `WinActivate, ahk_id %PMCWinID%` should work. You can also use the floating toolbar.
