### ISSUE TITLE
UI Bug - Toolbar Icons

### ISSUE THREAD

**Issue by njwolff** [Pulover/PuloversMacroCreator#195]
I'd like to report a visual bug in the program where the icons don't appear correctly and even worse when you try to change the icon size it works in reverse. Could you please check them out and fix them in the upcoming update?

Big Icons selected: ![Pulover's Macro Creator UI Bug - Big Icons](https://user-images.githubusercontent.com/92811369/137948094-cab639c0-cce5-4513-8ce8-be1f4686608b.png)
Small Icons selected: ![Pulover's Macro Creator UI Bug - Small Icons](https://user-images.githubusercontent.com/92811369/137948098-fec2a7dc-e70c-4087-8966-3f71e17497b3.png)

**Comment by Pulover** [comment]
I'm not sure that this is a bug or that it can be fixed. Maybe it has to do with your resolution or some other settings. You can click on View > Reset Layout to return them to their position but surely it's not working in reverse like you said.
