### ISSUE TITLE
Bloatware bundled with latest installer.

### ISSUE THREAD

**Issue by AndrewDTR** [Pulover/PuloversMacroCreator#196]
Hey, just went to download the latest version as prompted by the software and got some bloatware installed on my device. Not sure if this is intentional or if it comes pre-bundled with something, just wanted to bring it to your attention.

**Comment by AndrewDTR** [comment]
...just gonna close the issue? That's awfully shady.

**Comment by claell** [comment]
Does one have to confirm this (is opt out possible)?

**Comment by claell** [comment]
Just had a look myself. At least it seems that in the installer, one can decline the installation of the "Optional Offer" ("Adaware Web Companion" for me).

**Comment by mark-wiemer** [comment]
Fixed: https://github.com/mark-wiemer/adware-free-macro-creator/releases/tag/v5.4.2
