### ISSUE TITLE
Strange/catchy virus? js error messages on startup

### ISSUE THREAD

**Issue by Kongolan** [Pulover/PuloversMacroCreator#198]
When i ran it, it tried to open a few js scripts on websites like this: https://github.githubassets.com/assets/environment-2bf92300.js
But reported some fails. These scripts seem catchy for me.

Findings on the web: 
1) https://www.hybrid-analysis.com/sample/d0f3637b737ea5d12187b0dc3d251dba81cafd1946f7a4514de08584b2b4bd46/61aad1e3ae0b36336530ed06
2) https://github.com/initstring/passphrase-wordlist/issues/3

Version: 5.0.5

**Comment by Pulover** [comment]
I don't recognize this script, you probably downloaded a modified version or you've come to the wrong repository. I suggest you remove what you have installed and download the latest version from my website or from github itself.

**Comment by Kongolan** [comment]
Might be true, I don't know where I pulled it from one year back. But it showed that scripts before the update window with the new version showed up. (In case someone has a similar problem in the future.)

I can also pass you the version, I still have, if you need.
