### ISSUE TITLE
OCR + ComObj

### ISSUE THREAD

**Issue by reaperisonline** [Pulover/PuloversMacroCreator#201]
Hi,

I have an issue with OCR and ComObj.

**OCR only works when i run administrator mode.**

![image](https://user-images.githubusercontent.com/47637050/147752494-92223918-51ab-44d0-b386-d532c7c155cc.png)

**ComObj (with excel) only works in normal mode.**

![image](https://user-images.githubusercontent.com/47637050/147752556-815a0dc7-5b86-4c5d-9d2d-66d071574504.png)
![image](https://user-images.githubusercontent.com/47637050/147756937-6acfa112-bf8c-4726-97bf-c879f6b057f1.png)

Here is the setup:
![image](https://user-images.githubusercontent.com/47637050/147754236-b86e3fa1-e65c-45a4-990e-b667bd9269ea.png)

I need to be able to use both functions, what can I do to solve this?

**Comment by Pulover** [comment]
I wish I had a solution for you but really don't know how to solve this situation. Maybe running excel as admin as well could work, but can't test it.

**Comment by reaperisonline** [comment]
That's okay. I really appreciate the quick reply! You probably hear this a lot, but i love your program. Thanks a lot :)

I'll see what i can do to fix this and report back. It works fine on my own computer. Just the work computer being annoying.
