### ISSUE TITLE
Feature Request: Delete old Image or Replace image when screenshotting again under the same action

### ISSUE THREAD

**Issue by ss7vegetto** [Pulover/PuloversMacroCreator#203]
Whenever I am updating my macro's images because of a new patch or for whatever reason... the screenshot tool generates a new image instead of deleting/replacing the image to be searched.  Over the past year that I've been using this function for a game, with multiple macros.... I have a library of over 1000+ images due to this, not knowing which to delete and which to keep.

**Comment by Pulover** [comment]
Sorry but there's no safe way for the program to know that the file is not being used somewhere else or even in another project.

**Comment by ss7vegetto** [comment]
Would it be possible to have an event like On-Screen cap, check if there was an old value/path already in the field or macro then delete the file that it was pointing to?

Thanks for responding, I didn't think this was going to be looked at. Much appreciated.

**Comment by Pulover** [comment]
Consider the following situation: you have line of ImageSearch working and then you duplicate that line to add a new search, edit the new line and take a new screenshot. If it deletes the file that's in the Input field the previous command won't work anymore.

You're welcome.

**Comment by ss7vegetto** [comment]
ah... lol ok. yeah that'd make a mess of things. 
For the time being, I've made a macro to delete the file path in my clipboard so that should suffice on my side.
What about making the function to delete previous image when CTRL is held before clicking the screencap button?

**Comment by Pulover** [comment]
No, I don't think so. You've solved your problem well already, I think.
