### ISSUE TITLE
Hotkeys not pulling over to new defined hotkeys for various macros

### ISSUE THREAD

**Issue by ghyujkilop** [Pulover/PuloversMacroCreator#204]
I have 4 macros and I just changed the order of them as they were listed by date/time created. I then re-assigned the hotkeys so that the f3,f4,f5 etc was in the order which I dragged and dropped them in. But what happens is when I press the hotkey f6 for instance, it corresponds to the old macros hotkey, not the new assigned macro.

Pls fix

**Comment by Pulover** [comment]
I cannot understand the problem therefore I cannot try to reproduce. You'll have to give more details.
