### ISSUE TITLE
Adaware Antivirus Bloating

### ISSUE THREAD

**Issue by Schlagbul** [Pulover/PuloversMacroCreator#212]
When you try to run the installer, there is a part where it adds "an additional offer" of Adaware Antivirus and it is automatticly installed on your computer if you click "Accept" but since most people leave everything as default, you probably have it installed without having knowledge of it.

**Comment by 0xRyanLucci** [comment]
shady

**Comment by jabbermacy** [comment]
PLENTY of shareware does this too, last time I checked this is 'free', don't like it don't use it
