### ISSUE TITLE
What is the maximum number of macros that can be generated?

### ISSUE THREAD

**Issue by LautermF** [Pulover/PuloversMacroCreator#214]
Hello,

I can't create any more macros in my project.
What is the maximum number of macros that can be created in Macrocreator?
I exported the .pmc file as .ahk and found 255 function returns.
Is this the maximum number?

Thanks for an answer!

**Comment by 0lm** [comment]
Wait what. Are you saying after creating a certain amount of macros, the software will be locked, like an expired trial?

**Comment by LautermF** [comment]
No, that's not what I want to say!
I'm just saying that I've found that a maximum of 255 macros can be created in PuloversMacroCreator.
Which I find quite a lot, but in my application I have just reached this limit.
I have seen absolutely nothing about PuloversMacroCreator getting banned or behaving like an expired trial. PuloversMacroCreator runs without problems! I just can't create more than 255 macros.
When I looked through the sources, I probably found the place where this limit is set. 
But I don't know the context of why this limit is entered there.

Thanks very much

**Comment by Pulover** [comment]
It's a limitation of the AutoHotkey language.

**Comment by LautermF** [comment]
OK.

Do I understand correctly that AutoHotkey does not allow more than a maximum of 255 macros?
In my use case, I have an AHK file that contains all macros. Shouldn't there be more than 255 there?

Or does this just have to do with the TabControl used in PuloversMacroCreator?

Thanks very much!

**Comment by Pulover** [comment]
It's a limitation of the Tab Control.

**Comment by LautermF** [comment]
OK.
This information helps me!
I will probably use PuloversMacroCreator to develop the macros, then export the macro as an AHK file and then attach it to my application.
I've looked in the AutoHotkey documentation to see if there is a maximum limit for macros, but couldn't find anything.

Thanks very much!
