### ISSUE TITLE
Backward compatibility of the .pmc files

### ISSUE THREAD

**Issue by mancevd** [Pulover/PuloversMacroCreator#22]
Hello,

After saving the .pmc file in 5.0 and opening in older PMC version, all the macros are shown only in 1 tab Macro1.
It is good to have backward compatibility for the future releases.

Thank you

**Comment by Pulover** [comment]
Hi,

The new version has features that are not supported in older versions so there's no way I can guarantee backward compatibility. Even for future releases there might be eventual changes in the pmc file if I find a problem that must be fixed or decide to implement a new command.
