### ISSUE TITLE
Cos() function always returning 1.000000

### ISSUE THREAD

**Issue by kaedog** [Pulover/PuloversMacroCreator#221]
when I multiply a variable (either by V := V*M or V *= M) before passing it through the Cos() function it always returns 1.000000
![bugexample](https://user-images.githubusercontent.com/104115926/164361135-d5bf51c2-ced3-42da-a912-2ef55bf4b2ce.png)

This doesn't happen when I pass it any other variable

very frustrating, seems like a bug. Anybody have ideas for workarounds? Thanks in advance

**Comment by kaedog** [comment]
Just to illustrate, here is the same script without the multiplication before the Cos():
![bugexample2](https://user-images.githubusercontent.com/104115926/164361432-99b7a194-0cb2-4deb-bddf-9c9194dd3cb8.png)

works like it should

**Comment by PaulCauchois** [comment]
The cosine function works as intended, it's just that you multiply r2 by 2pi beforehand. The cosine of an integer multiplied by 2pi is always 1, so it's completely logical it would return that value.
Short proof :
cos(2pi*n) = Re(e^(i*2pi*n)) = Re((e^i 2pi)^n) = Re(1^n) = 1^n = 1 given that n is an integer.

**Comment by kaedog** [comment]
Thank you for the explanation. I realize now that I just wasn't understanding the math. Sorry for posting this non-issue.
