### ISSUE TITLE
What is "webcompanion"?

### ISSUE THREAD

**Issue by DerfOh** [Pulover/PuloversMacroCreator#235]
Just a curious user, this software got installed when I last updated. Is this something that supports MacroCreator? I'm concerned because it appeared like it was installed via a macro without my consent 👎

**Comment by DerfOh** [comment]
Here's an image of the webpage I was dropped off at by the macro that ran with the MacroCreator update installer, I don't have screenshots of the application that was installed on my system as I removed it immediately with revo.
![image](https://user-images.githubusercontent.com/6360456/189369670-5f7a9936-b6d1-478d-b9e5-a5717baef12a.png)

**Comment by Pulover** [comment]
It's a spansored optional bundleware to support the developer. There is a user consent screen shown during installation with a decline button.

**Comment by DerfOh** [comment]
Okay I feel a bit better knowing it was added intentionally, I certainly could have missed the consent screen.

**Comment by AddisonG** [comment]
There is NO consent if you are upgrading from an older version.
It forces installation, and changes your search engine too.

It makes this software feel like a cheap 2000's application that installs toolbars.
