### ISSUE TITLE
Suspicious extension install on Google Chrome during Instalation

### ISSUE THREAD

**Issue by ghost** [Pulover/PuloversMacroCreator#239]
Hi,

When I was installing it, it tried to enable a suspicious extension on Google Chrome.

Could you please provide details on what is it, and why it is trying to install it?

**Comment by ghost** [comment]
Here is your installer on VirusTotal, it shows the presence of AdWare.
https://www.virustotal.com/gui/file/92ffa6da0bea664f2499cfbec2a578bf882ed861cbb218b384e6af6ea589dde9

**Comment by ghost** [comment]
After installing, and removing your program, I get this warnings in my computer:

![image](https://user-images.githubusercontent.com/6624087/192614598-a2a39c95-0143-44c0-a949-b03b05f2283e.png)

**Comment by ghost** [comment]
More metadata, I downloaded the installer from:
https://github.com/Pulover/PuloversMacroCreator/releases
Release v5.4.1 (commit b88433e)

**Comment by Pulover** [comment]
#235

**Comment by mark-wiemer** [comment]
Fixed: https://github.com/mark-wiemer/adware-free-macro-creator/releases/tag/v5.4.2, this version does not try to install Web Companion or any other bloatware
