### ISSUE TITLE
Web Companion PUP Packaged with Installer

### ISSUE THREAD

**Issue by Foxxsayy** [Pulover/PuloversMacroCreator#241]
> Owner

Then why did it install even though I selected it to NOT install?

**Comment by Pulover** [comment]
#235

**Comment by Foxxsayy** [comment]
@Pulover I see that you marked [the forced install of viruses/PUPs is intentional](https://github.com/Pulover/PuloversMacroCreator/issues/239#issuecomment-1259999209)?

**Comment by Foxxsayy** [comment]
I can't even see the images I included since you closed it, so here they are again:

![image](https://user-images.githubusercontent.com/98929636/194088706-f6b973dd-f579-4bae-9972-dd4e0d25d7b9.png)

![image](https://user-images.githubusercontent.com/98929636/194088297-3e66f9e8-bd7b-447d-a6a9-947e11db81b0.png)

**Comment by mark-wiemer** [comment]
Fixed: https://github.com/mark-wiemer/adware-free-macro-creator/releases/tag/v5.4.2, this version does not try to install Web Companion or any other bloatware
