### ISSUE TITLE
Adware/Spyware Forced Install Still not Fixed, all issue reports related to it are closed asap without answer.

### ISSUE THREAD

**Issue by Foxxsayy** [Pulover/PuloversMacroCreator#243]
Previously I raised an issue about Adware/PUPs in your installer. You closed the issue with a link to another post about how viruses were getting installed with the macro recorder. 

You claim the adware is optional, but multiple accounts, including my own, report that the software installs even when you explicitly tell it not to. **Please respond to this issue. If you close the issue immediately again, I will be forced to report this repository.**

I've found quite a few reports with the same complaint, and virus scans reveal trojans, so I think GitHub will have plenty of evidence.

.
.

**Previous Post:**
––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––
As you can see, Pullover's Macro Creator installed the Web Companion PUP on my PC, which steals personal information among other things. Yours is the only thing I installed today (I believe the other two programs dated the 5th were a Microsoft official update and Firefox updating). I went to check the installer as it asked if I wanted to install another program and I selected NO, but it no longer has the request, I assume since the PUP is already installed.

I I downloaded from the [official list of downloads](https://www.macrocreator.com/download/) on the website.

**I see that other issues of the same complaint were closed without comment.** See **[here](https://github.com/Pulover/PuloversMacroCreator/issues/197)**, **[here](https://github.com/Pulover/PuloversMacroCreator/issues/196)**, and **[here](https://github.com/Pulover/PuloversMacroCreator/issues/212)**. I was excited to try this macro creator, but this is unacceptable and if you close this thread without comment, **I will be reporting your code on multiple sites.**  [This part I added later, after you closed the first one]

![image](https://user-images.githubusercontent.com/98929636/194088706-f6b973dd-f579-4bae-9972-dd4e0d25d7b9.png)

![image](https://user-images.githubusercontent.com/98929636/194088297-3e66f9e8-bd7b-447d-a6a9-947e11db81b0.png)

**Comment by Pulover** [comment]
It's a spansored optional bundleware to support the developer. There is a user consent screen shown during installation with a decline button.

![image (1)](https://user-images.githubusercontent.com/4416483/194739068-1804316d-be31-478b-84df-3c39aff6dbf3.png)

**Comment by Foxxsayy** [comment]
> It's a spansored optional bundleware to support the developer. There is a user consent screen shown during installation with a decline button.
> 
> ![image (1)](https://user-images.githubusercontent.com/4416483/194739068-1804316d-be31-478b-84df-3c39aff6dbf3.png)

This is exactly what I saw. I hit decline, and it still installed. Other people have said the same thing. One person reported it installed on an _update_. Additionally, **why is an adware well-known for _browser hijacking, cunning installation, malicious advertising and unprompted data tracking_" bundled with this in the first place?**

I was really excited to try this until Adaware installed itself, and god knows what other trojans and spyware came with that that I still haven't found. Maybe it's not you; maybe the program is coded to be able to install itself in bundles even when declined.

**Comment by Pulover** [comment]
No, it's not. If you chose Decline nothing else was installed. There's no malware in it. Why would I secretly install malware on people's computers? It's an open source project, you can download it and run from source or compile it yourself.

**Comment by Foxxsayy** [comment]
Should I see this every time I run the installer? Especially if both the Macro Recorder and Web Advisor are not installed?
 
> ![image (1)](https://user-images.githubusercontent.com/4416483/194739068-1804316d-be31-478b-84df-3c39aff6dbf3.png)

**Comment by Pulover** [comment]
It should show if web companion hasn't been installed because it should not make unauthorized changes. It won't show again if web companion is installed or if it has been uninstalled.

**Comment by Foxxsayy** [comment]
> It should show if web companion hasn't been installed because it should not make unauthorized changes. It won't show again if web companion is installed or if it has been uninstalled.

So the only way to try and recreate the issue is to install it on a brand new computer? What files are left behind after I uninstall it?

**Comment by Pulover** [comment]
Just a registry entry.

**Comment by Foxxsayy** [comment]
> Just a registry entry.

Do you know the path offhand? I haven't played with the program yet, but aside from the adware, it looks like it could be fantastic. It even has OCR and image recognition.


> No, it's not. If you chose Decline nothing else was installed. There's no malware in it. Why would I secretly install malware on people's computers? It's an open source project, you can download it and run from source or compile it yourself.

You didn't code Web Companion right? It's typically bundled with other stuff, I was trying to say perhaps it figured out a way to override the decline option.

**Comment by Pulover** [comment]
HKEY_LOCAL_MACHINE\SOFTWARE\Lavasoft\Web Companion
HKEY_LOCAL_MACHINE\SOFTWARE\WOW6432Node\Lavasoft\Web Companion

**Comment by andrehen** [comment]
I was not offered the option to skip the installation of this bloatware.... Luckily chrome alerted me some external program tried to install a add-on.
As this was my first time trying to use this software, I no longer have any interest of trying to use it..

**Comment by blahpers** [comment]
I have reported this repository to Github.  This is malware, particularly since there are reports that the software has installed itself despite being told not to.

It's 2023, there are better ways to make money than pulling one over on your users.  Do better or get booted.

**Comment by kendofriendo** [comment]
You need to remove it, jackass.

**Comment by Pulover** [comment]
I receive so many more complaints than compliments for the program in which I spent years devoloping and improving. Let alone donations. I have bills to pay, you know! I have a job to go about as well as other projects and I don't want to spend my free time working anymore. And I still have debts.

I'm not even working on Windows now. My laptop is broken. No one contributes with coding for this, donations are very occasional and rarely gives me a significant help.

I don't want to abandon this project, but it's so difficult to find motivation when I know that it has so many downloads everyday and still I get no help from users. And on top of that there are the people here on github cursing me for trying to make money out of my own work.

I've created PMC because I thought that everyone should have a free decent option for an automation program with an interface. Why don't pay for UiPath or something similar, then?

**Comment by Foxxsayy** [comment]
> I receive so many more complaints than compliments for the program in which I spent years devoloping and improving. Let alone donations. I have bills to pay, you know! I have a job to go about as well as other projects and I don't want to spend my free time working anymore. And I still have debts.
> 
> I'm not even working on Windows now. My laptop is broken. No one contributes with coding for this, donations are very occasional and rarely gives me a significant help.
> 
> I don't want to abandon this project, but it's so difficult to find motivation when I know that it has so many downloads everyday and still I get no help from users. And on top of that there are the people here on github cursing me for trying to make money out of my own work.
> 
> I've created PMC because I thought that everyone should have a free decent option for an automation program with an interface. Why don't pay for UiPath or something similar, then?

@Pulover I respect the hell out of indie devs and open source software providers, and I completely empathize with the unfair beatings they sometimes get. And it sounds like you made to suffer the good intentions.

Even so, I have to chime in and say that this is not a trivial issue. Dozens of people have reported an unwanted install from your program, I've demonstrated previously that the program installed is known for being malicious, and your response has consistently been that it's the user's fault, there is no unwanted install, and even if there is, you have to make by other software.

It's totally valid need to make money. I wouldn't blame you for making a paid program. However, when you ignore dozens of user complaints and comments detailing the same issue over several threads, which reiterate the same thing from different people, it is difficult to believe that you aren't aware of the issue and either lying or willfully ignoring it.

I tried your software once, but removed it and go back once I saw installed malware/adware. Even if it really is optional...bundling known malware is untrustworthy. If you had responded by telling me you'd fix it, I'd probably have been fine, but you doubled down and insisted everyone else is wrong. And your audience is mostly power users and above...what are the odds all of us accidentally clicked the wrong button? 

Looking at it from the issues you listed:

- Why would people donate to a free project that bundles adware?
- Why would coders contribute to a program that installs adware?

There has to be another way you can monetize. Doing it the way you are now might even be driving away the users and coders you'd like to attract.

**Comment by mark-wiemer** [comment]
FYI, I'm working on fixing this in https://github.com/mark-wiemer/adware-free-macro-creator. No promises!

**Comment by mark-wiemer** [comment]
Fixed: https://github.com/mark-wiemer/adware-free-macro-creator/releases/tag/v5.4.2
