### ISSUE TITLE
Remove bundled malware from installer

### ISSUE THREAD

**Issue by c3f59** [Pulover/PuloversMacroCreator#252]
I installed this from the installer linked on github and it installed an app called Web Companion plus associated browser extensions without asking permission. Please do not bundle your software with crap.

**Comment by Pulover** [comment]
https://github.com/Pulover/PuloversMacroCreator/issues/243#issuecomment-1789452738

**Comment by mark-wiemer** [comment]
FYI, I'm working on fixing this in https://github.com/mark-wiemer/adware-free-macro-creator. No promises!

**Comment by mark-wiemer** [comment]
Fixed: https://github.com/mark-wiemer/adware-free-macro-creator/releases/tag/v5.4.2
