### ISSUE TITLE
Pulover's Macro Creator installs web companion without warning

### ISSUE THREAD

**Issue by Symnok** [Pulover/PuloversMacroCreator#263]
Pulover's Macro Creator installs web companion without warning.
The installer does not even warn the user about installation of "Web Companion".

**Comment by Pulover** [comment]
Yes, it does. #243

![image (1)](https://user-images.githubusercontent.com/4416483/194739068-1804316d-be31-478b-84df-3c39aff6dbf3.png)

**Comment by mark-wiemer** [comment]
Fixed: https://github.com/mark-wiemer/adware-free-macro-creator/releases/tag/v5.4.2, this version does not try to install Web Companion or any other bloatware
