### ISSUE TITLE
Any ethical fork out there?

### ISSUE THREAD

**Issue by dhyanKaro** [Pulover/PuloversMacroCreator#271]
One which doesn't include the bundled Adware?

**Comment by ozzhates** [comment]
I've followed the documentation to compile it without the installer declaration dialogue. I have also just clicked _Decline_ when I was feeling lackadaisical.

**Comment by mark-wiemer** [comment]
You can see my copy, https://GitHub.com/mark-wiemer/adware-free-macro-creator :) the release includes an installer, a zip, and instructions to compile from source :)
