### ISSUE TITLE
Problem after closing 1 macro 

### ISSUE THREAD

**Issue by mancevd** [Pulover/PuloversMacroCreator#29]
Hi,

In the new version if you have open multiple macros and you try to close one, it mess up the codes and commands of other macros by moving commands from 1 macro to other macros.

I have created a video to illustrate the problem with dummy data https://youtu.be/ko2m6_zM-p0 .
Thank you.

**Comment by Pulover** [comment]
Hi mancedvd,

Thank you for the report. I was able to reproduce it here and will fix it for the next update.

**Comment by Pulover** [comment]
Fixed in v5.0.2.
