### ISSUE TITLE
Autohotkey environment variables not working properly

### ISSUE THREAD

**Issue by Etuldan** [Pulover/PuloversMacroCreator#3]
According to this : http://www.autohotkey.com/docs/Variables.htm#WorkingDir
A_WorkingDir and A_ScriptDir should, IMO, be setup by default to the directory of the selected PoluversMacroCreator script.

My testing script : 
[PMC Code]|F3||1|Window|1
1|[Pause]|WorkingDir : %A_WorkingDir%`nScriptDir : %A_ScriptDir%|1|0|MsgBox|1||||

I expect to get "D:\profils\arg\Mes documents" (the location of the script) but the popup indicates me "C:\Program Files\MacroCreator" (the location of the installation path of PuloversMacroCreator)

![puloverbug](https://f.cloud.github.com/assets/4972105/767212/0def9102-e87a-11e2-9e99-05fdd13fcfa1.JPG)

**Comment by m1r0** [comment]
This problem is still present if you run the script through the command line, for example:

```
"C:\Program Files\MacroCreator\MacroCreator.exe" "C:\Users\Administrator\Desktop\Boot.pmc" -s1
```

In this case the `A_WorkingDir` and `A_ScriptDir` are poiting to `C:\Program Files\MacroCreator`.
