### ISSUE TITLE
Random device sounds, softlocks laptop when keyboard unplugged

### ISSUE THREAD

**Issue by nyanpasu64** [Pulover/PuloversMacroCreator#35]
I have a Windows 10 touchscreen laptop. PMC 5.0.4.

Whenever I have PMC open and a hub plugged in, I hear random device sounds. USBLogView shows no events.

When I unplug my keyboard with PMC open, PMC crashes, and the Windows crash dialog (close window...) freezes (Not Responding). Every app I try to subsequently click on freezes as well. The taskbar does nothing. Oddly enough, I can still scroll (but not click) with the touchscreen, and trails are visible. Unplugging or plugging the external monitor is handled normally, but input is entirely broken, necessitating a restart.

I think PMC corrupts Windows input state, leading to these input issues.

Possibly related to #34

**Comment by jimbo1qaz** [comment]
Confirmed random device sounds in 5.0.5. I don't want to crash my computer right now, though, so I can't test part 2.

**Comment by Pulover** [comment]
I unplugged my keyboard with PMC open and nothing happened. It must be a conflict with some other software or hardware you have.

**Comment by davidbgeek** [comment]
Just discovered that it's potentially caused by my wireless Micrsofot keyboard/mouse combo.

**Comment by jimbo1qaz** [comment]
I have a Microsoft Natural keyboard of some sort, along with a Logitech trackball (with built-in back/forward keyboard device). They don't cause problems by themselves, only when PMC is running.

**Comment by davidbgeek** [comment]
Same here.
