### ISSUE TITLE
having problem EMmu emulator 

### ISSUE THREAD

**Issue by lakashmi** [Pulover/PuloversMacroCreator#37]
I am unable to use this pullover software in this EMmu Android Emulator .  Please help me out . Could you fix this problem. That will be great .

**Comment by Pulover** [comment]
Hello, 

I'm sorry but this is not a problem that can be fixed. AutoHotkey simply doesn't work on some applications, especially Java based. You may try to ask in the AHK forum if anyone knows a workaround.

**Comment by lakashmi** [comment]
I am having another problem ..please help me! I wanted to do something like
that if the picture shot does not find then the selected else process will
be repeated until find the actual picture .when the picture will be found
it will continue.. Could you help me please how to do that ?

**Comment by Pulover** [comment]
Put inside an infinite loop and use `break` when the image is found.

**Comment by lakashmi** [comment]
I am apologizing in order to forget to thank you . The excellent software
you have made. I have no words to express.. you make our work so much
easier. It helps us a lot and still helping us . I am seriously going to
donate! wonderful. keep updating . Thank you very very much ! love you !

On Sun, Sep 4, 2016 at 4:42 PM, Rodolfo U. Batista <notifications@github.com
