### ISSUE TITLE
Playback for Mouse Doesn't work for Minecraft

### ISSUE THREAD

**Issue by Markersx** [Pulover/PuloversMacroCreator#38]
I think it's because the mouse in minecraft is always snapped back to the center so when ever you move it away it goes back. You can test this by opening your inventory moving your mouse to the side then close and reopen your inventory. I think a good way to fix it would be to have an option where after every mouse event it would set the origin position back to the center.

**Comment by Markersx** [comment]
I have figured out how to do it but it derp.

**Comment by Pulover** [comment]
Good to know you solved it yourself. Besides adding the command to itself, there's also an option in playback settings to return the mouse to starting position after the macro has finished.

**Comment by Markersx** [comment]
@Pulover Well it looks like i didn't figure it out i tried making the mouse movements relative but then it only moves the mouse a couple frames. When im in game the mouse is always at X963 Y565 and when i move it around it stays there. What do you mean by "Besides adding the command to itself"

**Comment by Markersx** [comment]
so basically when i hit record go into game i try to move the mouse but it snaps back to the same position so it only records little movement how can i fix that?

**Comment by Pulover** [comment]
I meant to add a command to move the mouse back to center, but I see now that this is not what you need. PMC is not designed specific for games, so I don't have a solution for that... The recorder uses MouseGetPos so it won't record movements in the game, but you can try the Relative Recording option. Default method is to hold CapsLock, but you can change it to toggle mode in Recording Settings. That way it will record mouse movements relative to the current position when CapsLock is on.

**Comment by Markersx** [comment]
I tried setting caps lock to toggle but it still just stutters but its ok because I just found a way to still be able to do the actions I want without having to move the mouse around.

**Comment by Pulover** [comment]
This is a recurrent problem in games where you control the camera with mouse movements. There might be better solutions using ahk scripts, you just have to google on the ahk forums.
