### ISSUE TITLE
When using RegExMatch, unable to view pattern match in variable. 

### ISSUE THREAD

**Issue by ivnacevedo** [Pulover/PuloversMacroCreator#39]
Hello,

The following is not displaying the pattern match in the message box when using MacroCreator:
`RegExMatch("xxxabc123xyz", "abc.*xyz", _)`
`MsgBox, 0, , %_%`

It should display abc123xyz but instead the message box is blank.

When running the same code in a regular autohotkey script the message box does display abc123xyz.

Thanks

**Comment by Pulover** [comment]
Due to restrictions on how dynamic variables work, an underscore cannot be used as outputVar.

**Comment by Pulover** [comment]
PMC runs functions dynamically using an Eval() function, so outputVars are not not supported. But I agree that it should work, so I'm going to leave this issue open and see if I can cover such cases in a future release.

**Comment by Pulover** [comment]
Implemented in v5.1.2 for the **Function** window.
