### ISSUE TITLE
Language Error

### ISSUE THREAD

**Issue by premiumcarrot** [Pulover/PuloversMacroCreator#41]
for some reason, this error pops up when i try to install it on my corporate computer. 

i'm using autohotkey, so while its okay- it certain slows things down a little bit... not that much since i'm not very familiar with your software either!

cheers

![error](https://cloud.githubusercontent.com/assets/23151350/19837148/958acbd0-9eee-11e6-8984-4dcdb1f7ff3a.JPG)

**Comment by premiumcarrot** [comment]
i should add that "no" ends the script. if i click yes, another error message pops up and ends the start up for the program. i forgot to take a screenshot of the 2nd error. i'll post again.

**Comment by amjimmy** [comment]
I am experiencing the same issue. Somebody help?
