### ISSUE TITLE
Command parameters "-sN" not work on win10

### ISSUE THREAD

**Issue by hitvery** [Pulover/PuloversMacroCreator#43]
I want to add a schedule macro to Window's Task Scheduler, using the button "Schedule Macros" within “File”. But nothing happened when the schedule time arrived... Then I tried to run the command manually, no response neither. The parameter "-aN" is valid. My environment is win10 64bit.

**Comment by Pulover** [comment]
You might need to edit the task in windows scheduler to add admin rights or password. Windows policies changes over time, I cannot guarantee that this function will always work.
