### ISSUE TITLE
Send text (Paste from Clipboard) reliability could be improved easily

### ISSUE THREAD

**Issue by Xpyder** [Pulover/PuloversMacroCreator#44]
I've been having the Send Text (Paste form Clipboard) behave unreliably.  Most of the time it sends correctly, but sometimes it sends nothing, and other times it sends what was on the clipboard not the text listed in the macro.

The reliability of this could be greatly improved by changing this

```
	pb_Clipboard:
		SavedClip := ClipboardAll
		If (Step != "")
		{
			Clipboard =
			Clipboard := Step
			Sleep, 333
}
```

to this
```
	pb_Clipboard:
		SavedClip := ClipboardAll
		If (Step != "")
		{
			Clipboard =
			Clipboard := Step
			ClipWait, 1, 1
}
```

**Comment by Xpyder** [comment]
I found that in Playback.ahk

Also to be clear, I'm not positive that's the file the translation is building from, but regardless of the correct location the change would be the same (changing sleep to clipwait)

**Comment by Pulover** [comment]
I found that the whole problem was caused by the code trying to restore the original clipboard content. I think this is unnecessary so I'm going to just let it replace it in the next release.

This was the best implementation in my tests:

```
	pb_Clipboard:
		If (Step != "")
		{
			Clipboard := ""
			Clipboard := Step
			Sleep, 1
		}
		If (Target != "")
		{
			Win := SplitWin(Window)
			ControlSend, %Target%, {Control Down}{v}{Control Up}, % Win[1], % Win[2], % Win[3], % Win[4]
		}
		Else
			Send, {Control Down}{v}{Control Up}
	return
```

**Comment by Pulover** [comment]
Adjustment applied in v5.1.2.
