### ISSUE TITLE
[Bug] Some keys don't record

### ISSUE THREAD

**Issue by Kristinita** [Pulover/PuloversMacroCreator#49]
### 1. Summary

If I press <kbd>Ctrl+Shift+P</kbd>, <kbd>p</kbd> key don't record for me in Pulover's Macro creator.

### 2. Steps to reproduce

I reproduce the problem in a version of Sublime Text without plugins and user settings.

I run Pulover's Macro Creator → I click to «Record» button →

![Record](http://i.imgur.com/GTYG0jI.png)

`OK` → I press <kbd>F9</kbd> → I open any file in Sublime Text → I press <kbd>Ctrl+Shift+P</kbd> in Sublime Text

```python
key evt: shift+control+p
command: show_overlay {"overlay": "command_palette"}
```

→ I press <kbd>F9</kbd>.

### 3. Expected behavior

```autohotkey
WinActivate, D:\Киролайна\TheChorusGirl.Chekhov (DebugProject) - Sublime Text (UNREGISTERED) ahk_class PX_WINDOW_CLASS
Sleep, 984
Send, {LControl Down}
Sleep, 406
Send, {LShift Down}
Sleep, 110
Send, {p}
Sleep, 110
Send, {LShift Up}
Sleep, 15
Send, {LControl Up}
```

### 4. Actual behavior

<kbd>p</kbd> don't record.

```autohotkey
WinActivate, D:\Киролайна\TheChorusGirl.Chekhov (DebugProject) - Sublime Text (UNREGISTERED) ahk_class PX_WINDOW_CLASS
Sleep, 984
Send, {LControl Down}
Sleep, 406
Send, {LShift Down}
Sleep, 110
Send, {LShift Up}
Sleep, 15
Send, {LControl Up}
```

### 5. Environment

**Operating system and version:**
Windows 10 Enterprise LTSB 64-bit EN
**Sublime Text:**
Build 3126
**AutoHotkey:**
 1.1.25.01
**Pulover's Macro Creator:**
5.0.5 (x64)

Thanks.

**Comment by Pulover** [comment]
Doesn't seem to be an issue (anymore). Tested on Sublime, Windows 10.

Note: If you have a different keyboard layout, try changing it to EN.
