### ISSUE TITLE
Macros overwritten when closing v5.0.5

### ISSUE THREAD

**Issue by Raddan** [Pulover/PuloversMacroCreator#50]
When closing a macro it moves and overwrites to the next macro.

1. Load .pmc
2. Close Macro1
3. Macro1 closes but it is transferred and overwrites macro2 

Does not appear to happen with all saved macros so I've attached this one that is bugged for me.
[ESO Set List.zip](https://github.com/Pulover/PuloversMacroCreator/files/971959/ESO.Set.List.zip)

**Comment by Pulover** [comment]
I've confirmed this bug and have made some changes for the next release that have fixed it, apparently.

**Comment by Pulover** [comment]
Fixed in v5.1.2.
