### ISSUE TITLE
Not recording mouse clicks on On-Screen Keyboard

### ISSUE THREAD

**Issue by wheelerlaw** [Pulover/PuloversMacroCreator#52]
If I open the On-Screen Keyboard and I click on keyboard keys, the corresponding mouse clicks are not recorded.

**Comment by Huang-CL** [comment]
Have the same problem here.

**Comment by Pulover** [comment]
Probably an issue with MS accessibility policies for the virtual keyboard. But why not use the Text command window anyway?
