### ISSUE TITLE
Macro creator seems to close every time after I run a macro

### ISSUE THREAD

**Issue by f-camarillo** [Pulover/PuloversMacroCreator#53]
I will create a macro, and then click run. It will then run the macro, but the window for macro creator disappears, and the macro creator icon disappears from my taskbar making it seemed like the program closed. I then click on my Desktop icon to run it again, and nothing happens.

I checked my task manager, and it is still active even though I cannot open it. I have to manually end it, and then after that I can click on my desktop icon and it will open.

**Comment by ozzhates** [comment]
Make sure you have a winactive command calling the window you want to interact with so when u run your macro it focus on your work area. Also by default it uses a play control window separate from the main program for play,pause speed n stepping you could try turning it off and control from default assigned play/pause hotkeys. Lastly you could always use the ahk export option and try it outside of the macro creator with AHK. It's a great tool but remember everything it has just really high lights what auto hot key already has and all of it can programmed without pullovers GUI.

**Comment by Slapbox** [comment]
For me it gets stuck in the system tray. It's basically the same, must end process and restart.

**Comment by Tutunka** [comment]
Any resolution on this? Seems a lot of work and effort has been put into the app but I get this same issue on the latest version. I need to go to task manager, end process and start again. 
Must save script before running because the backup is always the demo script.

**Comment by dlopez831** [comment]
> For me it gets stuck in the system tray. It's basically the same, must end process and restart.

I have the same issue.

**Comment by tmplese** [comment]
Did you solve it already??

the trick is that when you run a macro, PMC will disappear and stay on the secondary programs section (close to the clock). It may appear like the PMC logo, a sand clock or a blue ▶️. Don't re open it since having two instances will make it crush. just right click and select expand or show.

**Comment by Slapbox** [comment]
There's no way to solve it to my knowledge. I just had to be extremely cautious in my usage, unfortunately.

**Comment by tmplese** [comment]
Would help if you record a video to demonstrate. By your description I don't think is a bug.

**Comment by Slapbox** [comment]
I assure you, it's a bug. It's been a long time since I've used it, but if I recall, after running a macro once and successfully hiding, the second time freezes or crashes the app. I really can't remember the specifics, but it's a bug.

**Comment by ferdok9** [comment]
It is not a bug, seriously it is a feature! The main window of "Pulover Macro Creator" is minimized in the tray bar in the bottom right corner of your desktop. It is not necessary to kill the process. You can click the up arrow to see all minimized programs there.  This functionality is enabled by default. You can disable it from "Options -> Minimize to tray".

**Comment by Slapbox** [comment]
@ferdok9, a process freezing _is a bug_. Being unable to restore it or operate it from the system tray _is a bug._

**Comment by Starlotte** [comment]
I was having the same problem but have since figured out what they mean. If you go to the show hidden icons button in the lower right corner of your screen, you can right click on the blue play button circle and click open window, meaning it's both intentional and a feature (as bad of a feature as it is).

**Comment by raz334** [comment]
Glad to see it's not just me having this problem..

I will also point out that i have experienced an issue where it will not detect and change windows, this ussually occurs just before it freezes up.

**Comment by Pulover** [comment]
Uncheck Options > Minimize to tray.
