### ISSUE TITLE
Second screen macro playback issue

### ISSUE THREAD

**Issue by ykit9** [Pulover/PuloversMacroCreator#54]
Have an issue after recording a macro on a two screens. Had to perform some operations on both screens. When playing that macro on a second screen mouse movements was ok. But after  clicking - mouse automatically moves to the first screen and perform recorded operations there.

**Comment by Pulover** [comment]
You'll probably face issues running recorded macros on a second screen. It's preferable to add commands on the list manually.

**Comment by Pulover** [comment]
I fogot to mention that you can change CoordMode to Screen in settings to make coordinates relative to your whole desktop area. There's also a command called CoordMode (in Run/Misc window) that you can use to change coord mode whenever you need to.
