### ISSUE TITLE
Exported AHK scripts does not work.

### ISSUE THREAD

**Issue by A-Charvin** [Pulover/PuloversMacroCreator#55]
The AHK files exported from the macro creator does not tends to work. 
-AHK is installed. the script launches but nothing else happens.

**Comment by KyleWJohnston** [comment]
To launch a macro from within an AHK file, you must first launch the file and then press the assigned key (usually F3). Can you share the AHK file or has the issue been resolved?

(I know this is an old issue, but it still has to be closed.)

**Comment by ozzhates** [comment]
An exported .pmc to .ahk will need to be modified. As an example expressions are not driven correctly.
 **Exported .PMC**
    _ExpressionPMC:
    BoxXAdd := %FoundX% + %Size%
    BoxYAdd := %FoundY% + %Size%
    EnvAdd, AddKey, 1
    BoxXMinus := %FoundX% - %Size%
    BoxYMinus := %FoundY% - %Size%_

**Modified to work with .AHK v1.1.29.01**
      _ExpressionAHK:
      BoxXAdd := FoundX + Size
      BoxYAdd := FoundY + Size
      EnvAdd, AddKey, 1
      BoxXMinus := FoundX - Size
      BoxYMinus := FoundY - Size_

If you spend little extra time learning AutoHotKey you can pick these problems up with ease.

**Comment by KHAGO** [comment]
I have same issue, when i create a long Macro, and it can run at PMC, but after export to AHK, it can not run, same issue as the demo version...
I was wondering it is not just simply the script not compile to the Autokey. How can it be solved...

**Comment by DavidTsangHW** [comment]
KyleWJohnston: I created a self executing EXE file by removing the assigned key. It works like a charm!

> To launch a macro from within an AHK file, you must first launch the file and then press the assigned key (usually F3). Can you share the AHK file or has the issue been resolved?
> 
> (I know this is an old issue, but it still has to be closed.)

![image](https://user-images.githubusercontent.com/12130884/67826968-49073f80-fb09-11e9-86f5-a83ecf18916e.png)
