### ISSUE TITLE
When editing the delay (ms) at bottom of the program. Pressing Enter, doesn't take attect.

### ISSUE THREAD

**Issue by Stamimail** [Pulover/PuloversMacroCreator#56]

**Comment by Stamimail** [comment]
There is another problem with this edit field (there is no tooltip for that, so I can't give it a name):
I'm using 2 langs: English and Hebrew.
I pressed: Ctrl+V
And I found, it up to the Keyboard Input:
Send, {Control Down}{**v**}{Control Up}
Sleep, 1000
Send, {Control Down}{**ה**}{Control Up}
Sleep, 1000

At bottom (edit field) written - Ctrl+V
At left side and in right side (code) written - Control + ה

**Comment by Pulover** [comment]
The only thing I suggest for this is changing keyboard layout. Controlling the InputBox to convert foreign keys is out of the question.
