### ISSUE TITLE
Looping Macro is Creating Extra Macros In Project

### ISSUE THREAD

**Issue by KDogHall** [Pulover/PuloversMacroCreator#59]
Attached is a macro I've made to help copy and paste content from websites to an excel sheet. I use a loop to copy and paste the content based on how many tabs are open in my browser window. The problem is, after I run either the "openLobbyContests" macro, or "openAllResults" macro, there are a bunch of new macros created within the project. It also seems to correlate to the number of times the macro loops. I.E., if the macro loops 150 times, then there are 150 new macro tabs within the project. Any ideas what could be happening?
[nba_log_v35.zip](https://github.com/Pulover/PuloversMacroCreator/files/1715304/nba_log_v35.zip)

**Comment by WilfordBrimley** [comment]
It's a piece of shit program with 0 support.

**Comment by Pulover** [comment]
@KDogHall your macro is too specific and complex for me to test. I'd need some short sample where I can reproduce and debug it in my own computer and see what's going on.

**Comment by ozzhates** [comment]
I get bashed daily for using PMC but I don't see anyone else coming up with anything even close in AutoHotkey.

**Comment by Pulover** [comment]
Thanks @ozzhates. Well, after 4 years I have found some time to make an update that is currently under tests for a closed few. I can't tell about this one but I believe the frequent crashes, corrupted files and some other bugs are fixed. If you'd like to help me test it, please get in touch. My official e-mail for this project should be working again but you can use any contact form you want.
Thanks for the help here, by the way.
