### ISSUE TITLE
Self Corrupting Files

### ISSUE THREAD

**Issue by joshuamcmahon** [Pulover/PuloversMacroCreator#60]
I'm having very strange issues, and I don't know if this should be defined as multiple incidents or if it is one systemic issue that is causing all the other problems.

When saving files or editing in pulover's macro creator, sometimes it will not accept changes to code. I can double click a variable for instance, type in a new value, but when I press Okay, it doesn't update. I will save the project, close, and reopen. It then appears to work fine, but if I begin to look through other macro tabs, I'll find that it did indeed accept my previous changes....by overwriting another part of the code. 

![ahk issue 1](https://user-images.githubusercontent.com/36638633/36387749-cf97253a-1567-11e8-863e-3a9cfde5f907.JPG)
In the above screenshot, I attempted to change the value of serverCount from 5 to 17...

![ahk issue 2](https://user-images.githubusercontent.com/36638633/36387750-cfabbd60-1567-11e8-925b-904c936dcc10.JPG)
When I reopened after saving I found the line had overwritten a dialog box on an entirely different tab.

Similar issues have cropped up in the past, where entire bodies of code have been spliced with other code on different tabs. I have reinstalled and tried using both x64 and x86 versions, but this does not seem to remedy the issue.

I can't seem to track down exactly what causes it, but once I cannot make changes or menu buttons stop working, it seems to indicate something is going to go wrong soon.

**Comment by WilfordBrimley** [comment]
Yeah this piece of shit has wasted tons of my time too.

**Comment by mjy9088** [comment]
Thanks to this ~f*****~ bug, I started using VCS

**Comment by Pulover** [comment]
Fixed in v5.1.2.
