### ISSUE TITLE
Right-click doesnt work after playing macro

### ISSUE THREAD

**Issue by Fennecai** [Pulover/PuloversMacroCreator#62]
When i use a "..." button to select a window, mouse coord, etc. when first opening the program on a fresh boot, it works. however, after i play the macro- regaurdless of using the button, the hotkey, etc. - that diologue doesnt work anymore. it shows that box with the informnation, but right-click no longer does anything and i have to press the esc key to get out of that "mode", which in turn leads to further problems.

**Comment by kodaman2** [comment]
I have a similar problem, I am unable to right click. Or really nothing works even when I try to do picture search region it won't let me click anywhere.

**Comment by Pulover** [comment]
I've identified a problem with the playback subroutine and have made a change to try to fix it. Will be in the next release for testing.

**Comment by Pulover** [comment]
Fixed in v5.1.2.
