### ISSUE TITLE
How can I input the ESC key?

### ISSUE THREAD

**Issue by Huang-CL** [Pulover/PuloversMacroCreator#64]
I need to input Esc key in my script.  When I recorded my inputs, I got something as follows. 

![image](https://user-images.githubusercontent.com/13855548/38461647-b45c4c8a-3a8a-11e8-9686-69356c863b37.png)

However, when I run the script, no Esc key is inputted.  And I can't find another way to set up the ESC key.

I'm on Windows 10 with PMC v5.0.5.  Thanks.

**Comment by KyleWJohnston** [comment]
I created a macro the same as yours above. The output AHK code was `Send, {Escape}`. I then opened a save dialog box, ran the macro, and this macro successfully closed it as expected.

Can you provide more detail on your issue?

**Comment by Huang-CL** [comment]
Thank you, Kyle.
I was creating a script for a game from the Microsoft store to avoid simple and repeat work.
Later on, I noticed that the `esc` problem only exists within the game.  It works outside the game.  The game takes other keyboard input from the macro.  Only `esc` doesn't work, as far as I noticed.

**Comment by minyan** [comment]
Use insert Keystroke.

**Comment by chends888** [comment]
If anyone is trying to use this in 2023:
- Add a Text command (Commands -> Text)
- In the dialog box select `Text with commands` instead of `Plain Text (Raw)`
- Add `{Escape}` to the input
