### ISSUE TITLE
Version 5.0.5 doesn't save "don't show warning about non-admin rights again" option state

### ISSUE THREAD

**Issue by Kyogre** [Pulover/PuloversMacroCreator#65]
Problem occurs both portable and setup version. If you launch MacroCreator with non-admin rights you will get warning, in which you can tick "don't show this again" option, but after relaunch of the program you will get that warning anyway even if you tick that option.

**Comment by Pulover** [comment]
Indeed the code for reading and writing this variable was lacking. Will be fixed in the next release. Thanks.

**Comment by Pulover** [comment]
Fixed in v5.1.2.
