### ISSUE TITLE
upon launch attempting to connect to macrocreator.com

### ISSUE THREAD

**Issue by pen25** [Pulover/PuloversMacroCreator#66]
i was notified by the companies IS team saying macrocreator.exe is attempting to reach out to macrocreator.com upon launch. I am thinking its the tip's that keep being displayed. i have unchecked the show tips but they keep appearing. is there any way of turning this off? any reason its attempting to contact the website?

**Comment by minyan** [comment]
It's auto updates feature, you can turn it off.
