### ISSUE TITLE
how to double click a .pmc file to run the macro script ?

### ISSUE THREAD

**Issue by adrianmak** [Pulover/PuloversMacroCreator#67]
as title

**Comment by minyan** [comment]
Use "Run"

**Comment by minyan** [comment]
At first i thought you were asking how to run PMC through the program.  
For that you can run it / open it with "Run"  
But on 2nd read, you probably asking why your .PMC files didn't get automatically executed by the program ?  
You need to set the .PMC files to be open with.....duh...this Macro Pulover program...is that kinda obvious ?

**Comment by mjy9088** [comment]
Install AutoHotKey and export the macro to ahk (or exe).

Double click the ahk (or exe) NOT PMC
