### ISSUE TITLE
script loses focus and doesnt find image after first image found

### ISSUE THREAD

**Issue by IIxauII** [Pulover/PuloversMacroCreator#71]
This is my current script
https://gyazo.com/9e430b70952d9357568a6b4480017f64
https://gyazo.com/dc394e7f57b4b3b318cb9466d455c1f2

When I run it, the first image gets found and the click gets executed. The next pixel which should be found is available after about ~30seconds of loading thats why the second pixelsearch has the loop statement (until errorlevel = 0).

My Problem is that it never finds the pixel on the second pixelsearch and when I left click out of the application while running the script it finds the pixel and jumps towards it (But the click command does not get registered by windows since it has lost the focus of the window). How can I avoide and solve this issue?

Sidenote: When I only run the Pixelsearch and comment out the rest of the code like this:
https://gyazo.com/ad20ac1693212322c52fd6697048d217
The programm runs through, detects the pixel and clicks on it.

**Comment by ozzhates** [comment]
Maybe I do not fully understand the problem but I feel like you should be using WinActivate to gain controlled focus on the window to be worked on. I know this is old. :man_shrugging:  https://autohotkey.com/docs/commands/WinActivate.htm

**Comment by Pulover** [comment]
I think this could be fixed by changing coordmode to screen on the pixel search command window.
