### ISSUE TITLE
Image Search / Pixel Search -> Select Region Button -> ToolTip Mistake

### ISSUE THREAD

**Issue by SERGEYZP** [Pulover/PuloversMacroCreator#72]
Version 5.0.5 (with admin rights)

For example en.lang:
d_Lang034 =	- Click and Drag with %DrawButton% to select area.
		- Click and release without dragging to select control area.
		- Click in an area without a control to select area of the window.

When ToolTip message appears on screen it don't retrieve the contents of variable %DrawButton%.
I check INI file, there present DrawButton=RButton in [Options] section.

Version 4.1.3 shows ToolTip message correctly.

**Comment by Pulover** [comment]
Fixed in v5.1.2.
