### ISSUE TITLE
How to automatically highlight code in right pane when selecting statement in left pane?

### ISSUE THREAD

**Issue by zxyzgt** [Pulover/PuloversMacroCreator#73]
I can't find the settings to automatically highlight code when selecting statement.
Also if the code is more than one page and I modified any statements at the beginning, the code always jumps to the end but not just focuses on where I was.

**Comment by mjy9088** [comment]
Feature request or question?

It's not feature of Pulover's Macro Creator

**Comment by Pulover** [comment]
That would be a nice feature to add. Will see what I can do.

**Comment by Pulover** [comment]
I'm afraid I have bad news...

After review the export function code and the Scintilla Wrapper options I don't think this will be possible.
One suggestion is using adding comments (Ctrl+L) to the lines in the list to help identify the parts of the code you want to. You can also add comment blocks clicking the `Insert` button on the same window.

**Comment by Pulover** [comment]
Well, I have good news now! I thought more about this and had another idea of how to implement this and it's working!
This feature will be added to the next release. Thanks for the suggestion, @zxyzgt.

**Comment by zxyzgt** [comment]
Great! Look forward to the updated release.

**Comment by Pulover** [comment]
Implemented in v5.1.2.
