### ISSUE TITLE
Unusable Currently

### ISSUE THREAD

**Issue by green4don** [Pulover/PuloversMacroCreator#74]
This application is essentially static and I'm not expecting any changes or improvements.
That said, having used it extensively for the first time the last two days, I'm not impressed.
There are quirks and omissions, but in the main it is a good tool.
My problem is that I keep forgetting to save every time I make a change.
This is a problem because, inevitably, the program will crash out on an edit or other problem just because.
The file recovery works, but the file is always very old, usually older than my last save.
Again, it crashed for me just now, and the actual source file is gone too.
So I'm back to this morning's backup and that's a lot of work to redo.
So, if you use this application you must save constantly and backup frequently.

**Comment by blueymcphluey** [comment]
I have a similar problem. I can run the macro once, but after that it just freezes up. If I go to the task manager, close it and then open again then I can run again.

Is there any hint on what could be causing this?

**Comment by lucius346346** [comment]
Do you guys have Areo disabled and/or classic theme enabled? For me every time I run and stop macro, toolbar became unresponsive but only when Areo is off.

**Comment by alexei9** [comment]
Just started using the tool this afternoon and although it was crashing fairly frequently as green4don described, I was able to complete my macro. Unfortunately after 3 hours of work, it decide to crash and delete the source file as well! I had presumed in spite of the regular crashes, my frequent saves would leave me with something to work with by unfortunately not!

This is unusable at present

**Comment by Pulover** [comment]
Fixed in v5.1.2. [Read more](https://www.macrocreator.com/2020/09/14/version-update-5-1-2/).
