### ISSUE TITLE
RegexMatch OutputVar is not recognized on PMC

### ISSUE THREAD

**Issue by minyan** [Pulover/PuloversMacroCreator#75]
I know this program doesn't actively developed anymore, just putting here just in case dev were back.  
Here the PMC file :  

`[PMC Code v5.0.5]||F7|1|Window,2,Fast,0,1,Input,-1,-1,1|1|Macro1
Groups=Start:1
1|RegExMatch|MatchPos := "abcXYZ123", "abc(.*)123", SubPat|1|0|Function|||||
2|[MsgBox]|%MatchPos% %SubPat1%|1|0|MsgBox|0||||
3|[Assign Variable]|Clipboard := Subpat1|1|0|Variable|||||

`
If it run through PMC, it doesn't recognize the OutputVar
![2](https://user-images.githubusercontent.com/829593/45859736-b2a50e00-bd8d-11e8-97eb-3195b6087479.jpg)

The AHK : 
`; This script was created using Pulover's Macro Creator
; www.macrocreator.com

#NoEnv
SetWorkingDir %A_ScriptDir%
CoordMode, Mouse, Window
SendMode Input
#SingleInstance Force
SetTitleMatchMode 2
#WinActivateForce
SetControlDelay 1
SetWinDelay 0
SetKeyDelay -1
SetMouseDelay -1
SetBatchLines -1

F3::
Macro1:
MatchPos := RegExMatch("abcXYZ123", "abc(.*)123", SubPat)
MsgBox, 0, , %MatchPos% %SubPat1%
Return

`
If the same instruction is export through AHK, it works.  
![1](https://user-images.githubusercontent.com/829593/45859740-c18bc080-bd8d-11e8-8b57-4cf59ec64388.jpg)

**Comment by Pulover** [comment]
Implemented in v5.1.2 for **Function** window.
