### ISSUE TITLE
autostart macro

### ISSUE THREAD

**Issue by itaybz** [Pulover/PuloversMacroCreator#77]
hey. I'm using your macro. BUT i want to use it to be triggered aumatiocally, i.e., when called from cmd (windows terminal) this will be executed by itself and not triggered manually. Is there a way to do that?

**Comment by Katie-S** [comment]
If you're calling it in the cmd terminal, wouldn't that be a manual trigger? What exactly do you mean by "called in the cmd terminal"?

**Comment by Pulover** [comment]
https://www.macrocreator.com/docs/Main.html#command-line-parameters
