### ISSUE TITLE
Mouse movement doesn't get recorded at all

### ISSUE THREAD

**Issue by Ayyyg** [Pulover/PuloversMacroCreator#79]
Tested various version and all recorded mouse move turn into `Click, X, Y` in command
does this software support MouseMove in AHK ?
some game won't pick up `Click, X, Y, 0` command
//
I can't use Find & Replace to replace command in this editor?
and there's no way to import ahk script only export?

**Comment by deepak21903** [comment]
I'm using it on remote office pc. mouse movement doesn't play. but everything else does
