### ISSUE TITLE
RegExMatch w/ leading zero

### ISSUE THREAD

**Issue by rbohlmann1** [Pulover/PuloversMacroCreator#80]
To reproduce BUG

Passcode := 012345
RegExMatch(Passcode, "\d{6}")

The leading zero is a legit digit, so it should pass, but it fails.   It works fine if exported to AHK and compiled, so it appears to be a PMC only issue.

BTW: Great tool!

Cheers,

Russell

**Comment by Pulover** [comment]
Hello,

This will only occur in expressions (using the Functions window gives the same result as in AHK). The problem however is in how AHK interprets this variable. It makes no distinction between numbers and strings until it's necessary to make an operation on the variable, so `RegExMatch` is evaluating the variable as a string.

In PMC, expressions are evaluated by my [Eval()](https://github.com/Pulover/Eval) function, which is pretty complex, and must be able to work with strings, numbers and objects, including math operations. If I change the behavior to keep a leading zero on a number, math operations will fail. Thus, I cannot "fix" this.

Thanks for the report anyway!
