### ISSUE TITLE
pulover "dissapears" when pressed "play current macro" button

### ISSUE THREAD

**Issue by abcboy515** [Pulover/PuloversMacroCreator#89]
![pulover](https://user-images.githubusercontent.com/59953108/72504083-1b17d880-3878-11ea-94da-09ec49c451bc.png)

Hi guys, i am trying to do a tutorial on youtube but my pulover keeps "disappearing" when i press play. i have to force end task it on task manager to restart it. pls advise

**Comment by ozzhates** [comment]
Why are you using run to open a web page? **F12** would help you create an _IE com object_ and has a checkbox for window wait. Also if it's disappearing to the tray try taking that selection off from the options menu, the option is called _**minimize to try**_. I know this software doesn't function the same on every system so on thing I've gotten used to having on is the **controls toolbar** this way if the script gets minimized automatically you can just click the furthest icon to the right to show/hide the main window.

**Comment by tmplese** [comment]
Exaxtly! The IE com is the way to go

**Comment by tmplese** [comment]
The "disappears when play" is default of Pulover. check the background programs running (you know, those hidden close to the clock)

**Comment by LucasaurusGrrrr** [comment]
> check the background programs running (you know, those hidden close to the clock)

Hello tmplese. I have the same problem. But what did you mean with "check the background programs running"?
Is there any possibility to avoid this?
Thanks for your help

**Comment by Pulover** [comment]
Uncheck Options > Minimize to tray.
