### ISSUE TITLE
Missing language files

### ISSUE THREAD

**Issue by FlemmingMC** [Pulover/PuloversMacroCreator#90]
Hi

After installation from PC administrator the program says "Missing language files - Would you loke to download them" (Yes/No).

If you choose No - the program do not start.
If you choose Yes and is not administrator you encounter an error.

If you are administrator program starts fine.
I triede to say no to check for new version, but still only admin can start the program :-(
![2020-01-20 12_44_05-](https://user-images.githubusercontent.com/60097838/72724482-b617f780-3b83-11ea-8934-2df0b394d40b.png)
![2020-01-20 12_44_18-Language Error · Issue #41 · Pulover_PuloversMacroCreator · GitHub – Google Chro](https://user-images.githubusercontent.com/60097838/72724483-b6b08e00-3b83-11ea-8037-9f1b00cd6381.png)

**Comment by tmplese** [comment]
Maybe you moved the .exe file to another folder? you have to keep all the files and folders in the same way as the application was un-zipped. If you move one thing, it'll stop working
