### ISSUE TITLE
open an internet page

### ISSUE THREAD

**Issue by zeus6999** [Pulover/PuloversMacroCreator#91]
Hi,I have a question
how do I open an internet page with your software?
Example: go to www.mylink.it
Regards

**Comment by ozzhates** [comment]
Hi zeus6999,
How I would do this is press **F12** to bring up the _internet explorer_ menu, make sure the drop-down menu has _navigate_ selected then you put www.mylink.it into the value box. Click Ok then run your macro.

**Comment by tmplese** [comment]
Hi! use the "internet explorer" button (logo of IE) or the "Run Command". No clicks needed

**Comment by tmplese** [comment]
Also, see the functionalities on "Run"... is the longest and most functionally rich command

**Comment by zeus6999** [comment]
Thanks for your answers
I would like to know, you can open a page in Chrome, for example kijiji.ca (I don't use internet explorer).

Thanks so much

**Comment by ozzhates** [comment]
try this include https://www.autohotkey.com/boards/viewtopic.php?t=42890

**Comment by zeus6999** [comment]
It's too complicated, I don't understand anything.
I have used Imacros for years, and only entered this line to open a link page in each browser
URL GOTO  = www.site..com

**Comment by tmplese** [comment]
Didnyou try using the "Run" command??

Try this:
1. create a chrome shortcut to your desktop
2. copy the shortcut path
 then, in PMC:
use the command "Run", paste the path abd try. If not, try looking for the chrome start file inthe chrome installation directory.

use run to execute chrome, add a pause to make sure it opens and then paste the URL you want to visit, hit enter and add a pause to wait the loading time

**Comment by Lucienest** [comment]
The simplest way you can do is:

_RUN_ **>** _Target_

> `chrome.exe "example.org"` **OR** `firefox.exe "example.org"`
