### ISSUE TITLE
Change the code

### ISSUE THREAD

**Issue by LucasaurusGrrrr** [Pulover/PuloversMacroCreator#92]
Hello, is it somehow possible to change the macro with the code?
That I can make the changes there, without searching for the actions on the left side and changing it there. Is this a setting I have to make? (Bc right now, I`m not able to make changes in the code on the right side).
Thanks for your help :)

**Comment by Pulover** [comment]
No. The preview panel is processed from the list panel. It doesn't work the other way around and parsing AHK scripts is virtually impossible.
