### ISSUE TITLE
Cannot execute script with Macro Recorder

### ISSUE THREAD

**Issue by zarma30** [Pulover/PuloversMacroCreator#93]
Hi

I created a script with the Macro Recorder [Mouse And Keyboard Macro Recorder v4.5]. This script works fine, if it s executed within the proper "Macro recorder" program.

However, if i try to execute the new created script with a command line : AutoHotkey.exe  XXXXXX
then each single function get an error. F.eg: 
```
PastaValue(v)
{
	clipboard = %v%
        Send("{Ctrl Down}v{Ctrl Up}")
	Send("{NumpadEnter}")
}
```

**Error: Call to nonexistent function.
Specifically: Send("{Ctrl Down}v{Ctrl Up}")**

i tried reinstall the program (_Autohotkey v1.1.32.00_) but always same error.

Thank you for your help!

**Comment by Pulover** [comment]
This is not a script created with PMC. You should ask at the AHK forum.
