### ISSUE TITLE
Crashing with no notification and DELETING BACKUP FILE in Windows 10

### ISSUE THREAD

**Issue by earhax** [Pulover/PuloversMacroCreator#94]
Not only does the app randomly crash, typically while I am working on a macro. But when it does, the backup file is DELETED!

Also, it has happened once that the actual Macro file I had loaded was ERASED! Somehow, when I reopened PMC and tried to reopen the pmc file I was using, it was simply gone - not in the recycle bin, not in the folder where I had it, just vanished!

Luckily, I had a recent backup to restore from or I would have been totally screwed.

I have come to be a heavy user of PMC. And other than these issues, I love the app! Hopefully this will be addressed and fixed soon. It's a lone blemish on an otherwise superb macro app!

**Comment by Pulover** [comment]
Fixed in v5.1.2. [Read more](https://www.macrocreator.com/2020/09/14/version-update-5-1-2/).
