### ISSUE TITLE
Your instructions are wrong and need to be updated

### ISSUE THREAD

**Issue by davidjkenner** [Pulover/PuloversMacroCreator#95]
I am new to your product. It looks good so I thought I would give it a try. I have done the following:
A. Spun up a new Windows 2019 server in AWS and RDP in
B. Downloaded and installed your product
C. Watched your video
D. Followed your instructions as follows:

The simplest way to get started with Pulover’s Macro Creator is using the recorder. Follow these steps record a macro:
1.Start Pulover’s Macro Creator.
2.Click on the Record button on the toolbar.
3.Press the record hotkey (default is F9).
4.Make mouse and keyboard actions.
5.Press the record hotkey again to stop.
6.Press the playback hotkey (default is F3) to reproduce your actions.

This is wrong! if you hit F9 it will NOT start the recorder. You have to have to go to Crtl+ R, then hit F10 (because your Demo is loaded) then hit F9

I then hit Windows + 1 (this launches Internet Explorer)
Then hit F9 (which is suppose to stop the macro)
Then if you hit F3 - it suppose run my macro but instead it runs your demo macro.

You have put a lot of work into the product but your documentation is lacking.

How do I Record and Playback a simple macro that will launch Internet Explorer?

Thanks

**Comment by davidjkenner** [comment]
Update. It writes the following code which does not run:

WinActivate, Pulover's Macro Creator ahk_class AutoHotkeyGUI
Sleep, 333
Sleep, 2766
Click, 892, -441, 0
WinActivate,  ahk_class Shell_TrayWnd
Send, {1}
Sleep, 234
Click, 900, 607, 0
Sleep, 78
WinActivate, Internet Explorer ahk_class IEFrame
Send, {LWin Up}

**Comment by Pulover** [comment]
> This is wrong! if you hit F9 it will NOT start the recorder. You have to have to go to Crtl+ R, then hit F10 (because your Demo is loaded) then hit F9
The instructions are correct. You missed one step: **Click on the Record button on the toolbar**

> You have put a lot of work into the product but your documentation is lacking.
It's a one man's work. Help is welcome.
