### ISSUE TITLE
Problem with SendRaw text

### ISSUE THREAD

**Issue by jimeex** [Pulover/PuloversMacroCreator#96]
Hello. 
When i'm trying to send rawtext somewhere, it don't work as expected. 
Example :
/tp @s ~ ~ ~ facing ~ ~ ~
but it never work.
I've tried multiple keyboards layouts (US,UK..)
But nothing is working. I understand that is it not possible to write special characters that's need commands.
But can you point me out a solution for this ? Before i was using another macro creator and i was able to set the clipboard. But i don't know how to do it with PMC.

Thanks

**Comment by jimeex** [comment]
Oh and i tried with "paste from clipboard" but it doesn't seem to work. I have to copy manually.

**Comment by Pulover** [comment]
I've tested you sample text and it's being sent but it's missing spaces and the last tilde indeed. However this is not a bug with PMC since the AHK script behaves exactly the same so it's not something that I can fix. You might want to ask/search about it at the ahk forum.
